namespace WindowsFormsApp3
{
    partial class Dashboard
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Dashboard));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.kryptonPalette1 = new ComponentFactory.Krypton.Toolkit.KryptonPalette(this.components);
            this.bunifuPanel5 = new Bunifu.UI.WinForms.BunifuPanel();
            this.dashboard_UC1 = new WindowsFormsApp3.Dashboard_UC();
            this.bunifuPanel6 = new Bunifu.UI.WinForms.BunifuPanel();
            this.bunifuPanel2 = new Bunifu.UI.WinForms.BunifuPanel();
            this.Date_dash = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.bunifuPanel4 = new Bunifu.UI.WinForms.BunifuPanel();
            this.label2 = new System.Windows.Forms.Label();
            this.bunifuPanel3 = new Bunifu.UI.WinForms.BunifuPanel();
            this.label1 = new System.Windows.Forms.Label();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.label3 = new System.Windows.Forms.Label();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.bunifuPictureBox1 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.Exit_dash = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Settings_dash = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.OrderHistory_dash = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Order_dash = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Customer_dash = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Products_dash = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Category_dash = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Dashboard_dash = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuPanel5.SuspendLayout();
            this.bunifuPanel6.SuspendLayout();
            this.bunifuPanel2.SuspendLayout();
            this.bunifuPanel4.SuspendLayout();
            this.bunifuPanel3.SuspendLayout();
            this.bunifuPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // kryptonPalette1
            // 
            this.kryptonPalette1.BasePaletteMode = ComponentFactory.Krypton.Toolkit.PaletteMode.Office2010Blue;
            this.kryptonPalette1.ButtonSpecs.FormClose.Image = ((System.Drawing.Image)(resources.GetObject("kryptonPalette1.ButtonSpecs.FormClose.Image")));
            this.kryptonPalette1.ButtonSpecs.FormClose.ImageStates.ImagePressed = ((System.Drawing.Image)(resources.GetObject("kryptonPalette1.ButtonSpecs.FormClose.ImageStates.ImagePressed")));
            this.kryptonPalette1.ButtonSpecs.FormClose.ImageStates.ImageTracking = ((System.Drawing.Image)(resources.GetObject("kryptonPalette1.ButtonSpecs.FormClose.ImageStates.ImageTracking")));
            this.kryptonPalette1.ButtonSpecs.FormClose.Orientation = ComponentFactory.Krypton.Toolkit.PaletteButtonOrientation.Inherit;
            this.kryptonPalette1.ButtonSpecs.FormClose.Style = ComponentFactory.Krypton.Toolkit.PaletteButtonStyle.Inherit;
            this.kryptonPalette1.ButtonSpecs.FormMax.Image = ((System.Drawing.Image)(resources.GetObject("kryptonPalette1.ButtonSpecs.FormMax.Image")));
            this.kryptonPalette1.ButtonSpecs.FormMax.ImageStates.ImageCheckedPressed = ((System.Drawing.Image)(resources.GetObject("kryptonPalette1.ButtonSpecs.FormMax.ImageStates.ImageCheckedPressed")));
            this.kryptonPalette1.ButtonSpecs.FormMax.ImageStates.ImagePressed = ((System.Drawing.Image)(resources.GetObject("kryptonPalette1.ButtonSpecs.FormMax.ImageStates.ImagePressed")));
            this.kryptonPalette1.ButtonSpecs.FormMax.ImageStates.ImageTracking = ((System.Drawing.Image)(resources.GetObject("kryptonPalette1.ButtonSpecs.FormMax.ImageStates.ImageTracking")));
            this.kryptonPalette1.ButtonSpecs.FormMax.Orientation = ComponentFactory.Krypton.Toolkit.PaletteButtonOrientation.Inherit;
            this.kryptonPalette1.ButtonSpecs.FormMax.Style = ComponentFactory.Krypton.Toolkit.PaletteButtonStyle.Inherit;
            this.kryptonPalette1.ButtonSpecs.FormMin.Image = ((System.Drawing.Image)(resources.GetObject("kryptonPalette1.ButtonSpecs.FormMin.Image")));
            this.kryptonPalette1.ButtonSpecs.FormMin.ImageStates.ImagePressed = ((System.Drawing.Image)(resources.GetObject("kryptonPalette1.ButtonSpecs.FormMin.ImageStates.ImagePressed")));
            this.kryptonPalette1.ButtonSpecs.FormMin.ImageStates.ImageTracking = ((System.Drawing.Image)(resources.GetObject("kryptonPalette1.ButtonSpecs.FormMin.ImageStates.ImageTracking")));
            this.kryptonPalette1.ButtonSpecs.FormMin.Orientation = ComponentFactory.Krypton.Toolkit.PaletteButtonOrientation.Inherit;
            this.kryptonPalette1.ButtonSpecs.FormMin.Style = ComponentFactory.Krypton.Toolkit.PaletteButtonStyle.Inherit;
            this.kryptonPalette1.ButtonStyles.ButtonForm.StateNormal.Back.Color1 = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(252)))), ((int)(((byte)(252)))));
            this.kryptonPalette1.ButtonStyles.ButtonForm.StateNormal.Back.Color2 = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(252)))), ((int)(((byte)(252)))));
            this.kryptonPalette1.ButtonStyles.ButtonForm.StateNormal.Back.ImageStyle = ComponentFactory.Krypton.Toolkit.PaletteImageStyle.Inherit;
            this.kryptonPalette1.ButtonStyles.ButtonForm.StateNormal.Border.DrawBorders = ((ComponentFactory.Krypton.Toolkit.PaletteDrawBorders)((((ComponentFactory.Krypton.Toolkit.PaletteDrawBorders.Top | ComponentFactory.Krypton.Toolkit.PaletteDrawBorders.Bottom) 
            | ComponentFactory.Krypton.Toolkit.PaletteDrawBorders.Left) 
            | ComponentFactory.Krypton.Toolkit.PaletteDrawBorders.Right)));
            this.kryptonPalette1.ButtonStyles.ButtonForm.StateNormal.Border.ImageStyle = ComponentFactory.Krypton.Toolkit.PaletteImageStyle.Inherit;
            this.kryptonPalette1.ButtonStyles.ButtonForm.StateNormal.Border.Width = 0;
            this.kryptonPalette1.ButtonStyles.ButtonForm.StatePressed.Back.Color1 = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(252)))), ((int)(((byte)(252)))));
            this.kryptonPalette1.ButtonStyles.ButtonForm.StatePressed.Back.Color2 = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(252)))), ((int)(((byte)(252)))));
            this.kryptonPalette1.ButtonStyles.ButtonForm.StatePressed.Back.ImageStyle = ComponentFactory.Krypton.Toolkit.PaletteImageStyle.Inherit;
            this.kryptonPalette1.ButtonStyles.ButtonForm.StatePressed.Border.DrawBorders = ((ComponentFactory.Krypton.Toolkit.PaletteDrawBorders)((((ComponentFactory.Krypton.Toolkit.PaletteDrawBorders.Top | ComponentFactory.Krypton.Toolkit.PaletteDrawBorders.Bottom) 
            | ComponentFactory.Krypton.Toolkit.PaletteDrawBorders.Left) 
            | ComponentFactory.Krypton.Toolkit.PaletteDrawBorders.Right)));
            this.kryptonPalette1.ButtonStyles.ButtonForm.StatePressed.Border.ImageStyle = ComponentFactory.Krypton.Toolkit.PaletteImageStyle.Inherit;
            this.kryptonPalette1.ButtonStyles.ButtonForm.StatePressed.Border.Width = 0;
            this.kryptonPalette1.ButtonStyles.ButtonForm.StateTracking.Back.Color1 = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(252)))), ((int)(((byte)(252)))));
            this.kryptonPalette1.ButtonStyles.ButtonForm.StateTracking.Back.Color2 = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(252)))), ((int)(((byte)(252)))));
            this.kryptonPalette1.ButtonStyles.ButtonForm.StateTracking.Back.ImageStyle = ComponentFactory.Krypton.Toolkit.PaletteImageStyle.Inherit;
            this.kryptonPalette1.ButtonStyles.ButtonForm.StateTracking.Border.DrawBorders = ((ComponentFactory.Krypton.Toolkit.PaletteDrawBorders)((((ComponentFactory.Krypton.Toolkit.PaletteDrawBorders.Top | ComponentFactory.Krypton.Toolkit.PaletteDrawBorders.Bottom) 
            | ComponentFactory.Krypton.Toolkit.PaletteDrawBorders.Left) 
            | ComponentFactory.Krypton.Toolkit.PaletteDrawBorders.Right)));
            this.kryptonPalette1.ButtonStyles.ButtonForm.StateTracking.Border.ImageStyle = ComponentFactory.Krypton.Toolkit.PaletteImageStyle.Inherit;
            this.kryptonPalette1.ButtonStyles.ButtonForm.StateTracking.Border.Width = 0;
            this.kryptonPalette1.FormStyles.FormCommon.StateCommon.Back.Color1 = System.Drawing.Color.FromArgb(((int)(((byte)(32)))), ((int)(((byte)(13)))), ((int)(((byte)(51)))));
            this.kryptonPalette1.FormStyles.FormCommon.StateCommon.Back.Color2 = System.Drawing.Color.FromArgb(((int)(((byte)(32)))), ((int)(((byte)(13)))), ((int)(((byte)(51)))));
            this.kryptonPalette1.FormStyles.FormCommon.StateCommon.Back.ImageStyle = ComponentFactory.Krypton.Toolkit.PaletteImageStyle.Inherit;
            this.kryptonPalette1.FormStyles.FormCommon.StateCommon.Border.DrawBorders = ((ComponentFactory.Krypton.Toolkit.PaletteDrawBorders)((((ComponentFactory.Krypton.Toolkit.PaletteDrawBorders.Top | ComponentFactory.Krypton.Toolkit.PaletteDrawBorders.Bottom) 
            | ComponentFactory.Krypton.Toolkit.PaletteDrawBorders.Left) 
            | ComponentFactory.Krypton.Toolkit.PaletteDrawBorders.Right)));
            this.kryptonPalette1.FormStyles.FormCommon.StateCommon.Border.GraphicsHint = ComponentFactory.Krypton.Toolkit.PaletteGraphicsHint.None;
            this.kryptonPalette1.FormStyles.FormCommon.StateCommon.Border.ImageStyle = ComponentFactory.Krypton.Toolkit.PaletteImageStyle.Inherit;
            this.kryptonPalette1.FormStyles.FormCommon.StateCommon.Border.Rounding = 10;
            this.kryptonPalette1.HeaderStyles.HeaderForm.StateCommon.Back.Color1 = System.Drawing.Color.FromArgb(((int)(((byte)(32)))), ((int)(((byte)(13)))), ((int)(((byte)(51)))));
            this.kryptonPalette1.HeaderStyles.HeaderForm.StateCommon.Back.Color2 = System.Drawing.Color.FromArgb(((int)(((byte)(32)))), ((int)(((byte)(13)))), ((int)(((byte)(51)))));
            this.kryptonPalette1.HeaderStyles.HeaderForm.StateCommon.Back.ImageStyle = ComponentFactory.Krypton.Toolkit.PaletteImageStyle.Inherit;
            this.kryptonPalette1.HeaderStyles.HeaderForm.StateCommon.Content.Padding = new System.Windows.Forms.Padding(10, -1, -1, -1);
            // 
            // bunifuPanel5
            // 
            this.bunifuPanel5.BackgroundColor = System.Drawing.Color.White;
            this.bunifuPanel5.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel5.BackgroundImage")));
            this.bunifuPanel5.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel5.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(252)))), ((int)(((byte)(252)))));
            this.bunifuPanel5.BorderRadius = 20;
            this.bunifuPanel5.BorderThickness = 0;
            this.bunifuPanel5.Controls.Add(this.dashboard_UC1);
            this.bunifuPanel5.Location = new System.Drawing.Point(267, 38);
            this.bunifuPanel5.Margin = new System.Windows.Forms.Padding(4);
            this.bunifuPanel5.Name = "bunifuPanel5";
            this.bunifuPanel5.ShowBorders = true;
            this.bunifuPanel5.Size = new System.Drawing.Size(1419, 800);
            this.bunifuPanel5.TabIndex = 30;
            this.bunifuPanel5.Click += new System.EventHandler(this.bunifuPanel5_Click);
            // 
            // dashboard_UC1
            // 
            this.dashboard_UC1.AutoValidate = System.Windows.Forms.AutoValidate.EnableAllowFocusChange;
            this.dashboard_UC1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(252)))), ((int)(((byte)(252)))));
            this.dashboard_UC1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dashboard_UC1.Location = new System.Drawing.Point(0, 0);
            this.dashboard_UC1.Margin = new System.Windows.Forms.Padding(5);
            this.dashboard_UC1.Name = "dashboard_UC1";
            this.dashboard_UC1.Size = new System.Drawing.Size(1419, 800);
            this.dashboard_UC1.TabIndex = 0;
            this.dashboard_UC1.Load += new System.EventHandler(this.dashboard_UC1_Load_1);
            // 
            // bunifuPanel6
            // 
            this.bunifuPanel6.BackgroundColor = System.Drawing.Color.Transparent;
            this.bunifuPanel6.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel6.BackgroundImage")));
            this.bunifuPanel6.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel6.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel6.BorderRadius = 0;
            this.bunifuPanel6.BorderThickness = 0;
            this.bunifuPanel6.Controls.Add(this.bunifuPanel2);
            this.bunifuPanel6.Controls.Add(this.bunifuPanel4);
            this.bunifuPanel6.Controls.Add(this.bunifuPanel3);
            this.bunifuPanel6.Dock = System.Windows.Forms.DockStyle.Top;
            this.bunifuPanel6.Location = new System.Drawing.Point(267, 0);
            this.bunifuPanel6.Margin = new System.Windows.Forms.Padding(4);
            this.bunifuPanel6.Name = "bunifuPanel6";
            this.bunifuPanel6.ShowBorders = false;
            this.bunifuPanel6.Size = new System.Drawing.Size(1416, 37);
            this.bunifuPanel6.TabIndex = 47;
            this.bunifuPanel6.Click += new System.EventHandler(this.bunifuPanel6_Click);
            // 
            // bunifuPanel2
            // 
            this.bunifuPanel2.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.bunifuPanel2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel2.BackgroundImage")));
            this.bunifuPanel2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel2.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel2.BorderRadius = 20;
            this.bunifuPanel2.BorderThickness = 1;
            this.bunifuPanel2.Controls.Add(this.Date_dash);
            this.bunifuPanel2.Location = new System.Drawing.Point(1068, 4);
            this.bunifuPanel2.Margin = new System.Windows.Forms.Padding(4);
            this.bunifuPanel2.Name = "bunifuPanel2";
            this.bunifuPanel2.ShowBorders = true;
            this.bunifuPanel2.Size = new System.Drawing.Size(335, 123);
            this.bunifuPanel2.TabIndex = 45;
            this.bunifuPanel2.Click += new System.EventHandler(this.bunifuPanel2_Click);
            // 
            // Date_dash
            // 
            this.Date_dash.BackColor = System.Drawing.Color.Transparent;
            this.Date_dash.BorderRadius = 17;
            this.Date_dash.Color = System.Drawing.Color.Transparent;
            this.Date_dash.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.Date_dash.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.Date_dash.DisabledColor = System.Drawing.Color.Gray;
            this.Date_dash.DisplayWeekNumbers = false;
            this.Date_dash.DPHeight = 0;
            this.Date_dash.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.Date_dash.FillDatePicker = false;
            this.Date_dash.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold);
            this.Date_dash.ForeColor = System.Drawing.Color.Black;
            this.Date_dash.Icon = ((System.Drawing.Image)(resources.GetObject("Date_dash.Icon")));
            this.Date_dash.IconColor = System.Drawing.Color.Black;
            this.Date_dash.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.Date_dash.LeftTextMargin = 5;
            this.Date_dash.Location = new System.Drawing.Point(23, -1);
            this.Date_dash.Margin = new System.Windows.Forms.Padding(4);
            this.Date_dash.MinimumSize = new System.Drawing.Size(4, 32);
            this.Date_dash.Name = "Date_dash";
            this.Date_dash.Size = new System.Drawing.Size(292, 32);
            this.Date_dash.TabIndex = 2;
            this.Date_dash.Value = new System.DateTime(2022, 10, 14, 13, 32, 0, 0);
            // 
            // bunifuPanel4
            // 
            this.bunifuPanel4.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.bunifuPanel4.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel4.BackgroundImage")));
            this.bunifuPanel4.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel4.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel4.BorderRadius = 20;
            this.bunifuPanel4.BorderThickness = 1;
            this.bunifuPanel4.Controls.Add(this.label2);
            this.bunifuPanel4.Location = new System.Drawing.Point(20, 4);
            this.bunifuPanel4.Margin = new System.Windows.Forms.Padding(4);
            this.bunifuPanel4.Name = "bunifuPanel4";
            this.bunifuPanel4.ShowBorders = true;
            this.bunifuPanel4.Size = new System.Drawing.Size(363, 73);
            this.bunifuPanel4.TabIndex = 46;
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.BackColor = System.Drawing.Color.Transparent;
            this.label2.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold);
            this.label2.Location = new System.Drawing.Point(13, 6);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(338, 23);
            this.label2.TabIndex = 1;
            this.label2.Text = "APICTURES - INVENTORY MANAGEMENT";
            // 
            // bunifuPanel3
            // 
            this.bunifuPanel3.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.bunifuPanel3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel3.BackgroundImage")));
            this.bunifuPanel3.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel3.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel3.BorderRadius = 20;
            this.bunifuPanel3.BorderThickness = 1;
            this.bunifuPanel3.Controls.Add(this.label1);
            this.bunifuPanel3.Location = new System.Drawing.Point(385, 4);
            this.bunifuPanel3.Margin = new System.Windows.Forms.Padding(4);
            this.bunifuPanel3.Name = "bunifuPanel3";
            this.bunifuPanel3.ShowBorders = true;
            this.bunifuPanel3.Size = new System.Drawing.Size(141, 123);
            this.bunifuPanel3.TabIndex = 46;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.BackColor = System.Drawing.Color.Transparent;
            this.label1.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold);
            this.label1.ForeColor = System.Drawing.Color.Black;
            this.label1.Location = new System.Drawing.Point(12, 6);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(118, 23);
            this.label1.TabIndex = 47;
            this.label1.Text = "DASHBOARD";
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(32)))), ((int)(((byte)(13)))), ((int)(((byte)(51)))));
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(32)))), ((int)(((byte)(13)))), ((int)(((byte)(51)))));
            this.bunifuPanel1.BorderRadius = 0;
            this.bunifuPanel1.BorderThickness = 0;
            this.bunifuPanel1.Controls.Add(this.label3);
            this.bunifuPanel1.Controls.Add(this.pictureBox1);
            this.bunifuPanel1.Controls.Add(this.bunifuPictureBox1);
            this.bunifuPanel1.Controls.Add(this.Exit_dash);
            this.bunifuPanel1.Controls.Add(this.Settings_dash);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel3);
            this.bunifuPanel1.Controls.Add(this.OrderHistory_dash);
            this.bunifuPanel1.Controls.Add(this.Order_dash);
            this.bunifuPanel1.Controls.Add(this.Customer_dash);
            this.bunifuPanel1.Controls.Add(this.Products_dash);
            this.bunifuPanel1.Controls.Add(this.Category_dash);
            this.bunifuPanel1.Controls.Add(this.Dashboard_dash);
            this.bunifuPanel1.Dock = System.Windows.Forms.DockStyle.Left;
            this.bunifuPanel1.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuPanel1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.bunifuPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuPanel1.Margin = new System.Windows.Forms.Padding(4);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(267, 828);
            this.bunifuPanel1.TabIndex = 28;
            this.bunifuPanel1.Click += new System.EventHandler(this.bunifuPanel1_Click);
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.BackColor = System.Drawing.Color.Transparent;
            this.label3.Font = new System.Drawing.Font("Segoe UI Semibold", 7.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.ForeColor = System.Drawing.SystemColors.ButtonHighlight;
            this.label3.Location = new System.Drawing.Point(94, 34);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(95, 19);
            this.label3.TabIndex = 1;
            this.label3.Text = "Administrator";
            // 
            // pictureBox1
            // 
            this.pictureBox1.BackColor = System.Drawing.Color.Transparent;
            this.pictureBox1.Image = global::WindowsFormsApp3.Properties.Resources.backg;
            this.pictureBox1.Location = new System.Drawing.Point(-180, 487);
            this.pictureBox1.Margin = new System.Windows.Forms.Padding(4);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(512, 336);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox1.TabIndex = 0;
            this.pictureBox1.TabStop = false;
            // 
            // bunifuPictureBox1
            // 
            this.bunifuPictureBox1.AllowFocused = false;
            this.bunifuPictureBox1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox1.AutoSizeHeight = true;
            this.bunifuPictureBox1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.bunifuPictureBox1.BorderRadius = 38;
            this.bunifuPictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("bunifuPictureBox1.Image")));
            this.bunifuPictureBox1.IsCircle = true;
            this.bunifuPictureBox1.Location = new System.Drawing.Point(13, 8);
            this.bunifuPictureBox1.Margin = new System.Windows.Forms.Padding(4);
            this.bunifuPictureBox1.Name = "bunifuPictureBox1";
            this.bunifuPictureBox1.Size = new System.Drawing.Size(77, 77);
            this.bunifuPictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox1.TabIndex = 0;
            this.bunifuPictureBox1.TabStop = false;
            this.bunifuPictureBox1.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // Exit_dash
            // 
            this.Exit_dash.AllowAnimations = true;
            this.Exit_dash.AllowMouseEffects = true;
            this.Exit_dash.AllowToggling = true;
            this.Exit_dash.AnimationSpeed = 200;
            this.Exit_dash.AutoGenerateColors = false;
            this.Exit_dash.AutoRoundBorders = false;
            this.Exit_dash.AutoSizeLeftIcon = true;
            this.Exit_dash.AutoSizeRightIcon = true;
            this.Exit_dash.BackColor = System.Drawing.Color.Transparent;
            this.Exit_dash.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.Exit_dash.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Exit_dash.BackgroundImage")));
            this.Exit_dash.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Exit_dash.ButtonText = "Log Out";
            this.Exit_dash.ButtonTextMarginLeft = 0;
            this.Exit_dash.ColorContrastOnClick = 45;
            this.Exit_dash.ColorContrastOnHover = 45;
            this.Exit_dash.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.Exit_dash.CustomizableEdges = borderEdges1;
            this.Exit_dash.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Exit_dash.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Exit_dash.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Exit_dash.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Exit_dash.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Exit_dash.Font = new System.Drawing.Font("Segoe UI Semibold", 8.25F, System.Drawing.FontStyle.Bold);
            this.Exit_dash.ForeColor = System.Drawing.Color.Black;
            this.Exit_dash.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Exit_dash.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Exit_dash.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Exit_dash.IconMarginLeft = 11;
            this.Exit_dash.IconPadding = 10;
            this.Exit_dash.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Exit_dash.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Exit_dash.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Exit_dash.IconSize = 25;
            this.Exit_dash.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.Exit_dash.IdleBorderRadius = 10;
            this.Exit_dash.IdleBorderThickness = 1;
            this.Exit_dash.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.Exit_dash.IdleIconLeftImage = null;
            this.Exit_dash.IdleIconRightImage = null;
            this.Exit_dash.IndicateFocus = true;
            this.Exit_dash.Location = new System.Drawing.Point(180, 60);
            this.Exit_dash.Margin = new System.Windows.Forms.Padding(4);
            this.Exit_dash.Name = "Exit_dash";
            this.Exit_dash.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Exit_dash.OnDisabledState.BorderRadius = 10;
            this.Exit_dash.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Exit_dash.OnDisabledState.BorderThickness = 1;
            this.Exit_dash.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Exit_dash.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Exit_dash.OnDisabledState.IconLeftImage = null;
            this.Exit_dash.OnDisabledState.IconRightImage = null;
            this.Exit_dash.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(114)))), ((int)(((byte)(30)))));
            this.Exit_dash.onHoverState.BorderRadius = 10;
            this.Exit_dash.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Exit_dash.onHoverState.BorderThickness = 1;
            this.Exit_dash.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(114)))), ((int)(((byte)(30)))));
            this.Exit_dash.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.Exit_dash.onHoverState.IconLeftImage = null;
            this.Exit_dash.onHoverState.IconRightImage = null;
            this.Exit_dash.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.Exit_dash.OnIdleState.BorderRadius = 10;
            this.Exit_dash.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Exit_dash.OnIdleState.BorderThickness = 1;
            this.Exit_dash.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.Exit_dash.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.Exit_dash.OnIdleState.IconLeftImage = null;
            this.Exit_dash.OnIdleState.IconRightImage = null;
            this.Exit_dash.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(114)))), ((int)(((byte)(30)))));
            this.Exit_dash.OnPressedState.BorderRadius = 10;
            this.Exit_dash.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Exit_dash.OnPressedState.BorderThickness = 1;
            this.Exit_dash.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(114)))), ((int)(((byte)(30)))));
            this.Exit_dash.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.Exit_dash.OnPressedState.IconLeftImage = null;
            this.Exit_dash.OnPressedState.IconRightImage = null;
            this.Exit_dash.Size = new System.Drawing.Size(67, 21);
            this.Exit_dash.TabIndex = 50;
            this.Exit_dash.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Exit_dash.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Exit_dash.TextMarginLeft = 0;
            this.Exit_dash.TextPadding = new System.Windows.Forms.Padding(0);
            this.Exit_dash.UseDefaultRadiusAndThickness = true;
            this.Exit_dash.Click += new System.EventHandler(this.bunifuButton8_Click);
            // 
            // Settings_dash
            // 
            this.Settings_dash.AllowAnimations = true;
            this.Settings_dash.AllowMouseEffects = true;
            this.Settings_dash.AllowToggling = true;
            this.Settings_dash.AnimationSpeed = 200;
            this.Settings_dash.AutoGenerateColors = false;
            this.Settings_dash.AutoRoundBorders = false;
            this.Settings_dash.AutoSizeLeftIcon = true;
            this.Settings_dash.AutoSizeRightIcon = true;
            this.Settings_dash.BackColor = System.Drawing.Color.Transparent;
            this.Settings_dash.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.Settings_dash.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Settings_dash.BackgroundImage")));
            this.Settings_dash.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Settings_dash.ButtonText = "Setings";
            this.Settings_dash.ButtonTextMarginLeft = 0;
            this.Settings_dash.ColorContrastOnClick = 45;
            this.Settings_dash.ColorContrastOnHover = 45;
            this.Settings_dash.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.Settings_dash.CustomizableEdges = borderEdges2;
            this.Settings_dash.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Settings_dash.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Settings_dash.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Settings_dash.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Settings_dash.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Settings_dash.Font = new System.Drawing.Font("Segoe UI Semibold", 8.25F, System.Drawing.FontStyle.Bold);
            this.Settings_dash.ForeColor = System.Drawing.Color.Black;
            this.Settings_dash.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Settings_dash.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Settings_dash.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Settings_dash.IconMarginLeft = 11;
            this.Settings_dash.IconPadding = 10;
            this.Settings_dash.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Settings_dash.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Settings_dash.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Settings_dash.IconSize = 25;
            this.Settings_dash.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.Settings_dash.IdleBorderRadius = 10;
            this.Settings_dash.IdleBorderThickness = 1;
            this.Settings_dash.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.Settings_dash.IdleIconLeftImage = null;
            this.Settings_dash.IdleIconRightImage = null;
            this.Settings_dash.IndicateFocus = true;
            this.Settings_dash.Location = new System.Drawing.Point(97, 60);
            this.Settings_dash.Margin = new System.Windows.Forms.Padding(4);
            this.Settings_dash.Name = "Settings_dash";
            this.Settings_dash.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Settings_dash.OnDisabledState.BorderRadius = 10;
            this.Settings_dash.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Settings_dash.OnDisabledState.BorderThickness = 1;
            this.Settings_dash.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Settings_dash.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Settings_dash.OnDisabledState.IconLeftImage = null;
            this.Settings_dash.OnDisabledState.IconRightImage = null;
            this.Settings_dash.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(114)))), ((int)(((byte)(30)))));
            this.Settings_dash.onHoverState.BorderRadius = 10;
            this.Settings_dash.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Settings_dash.onHoverState.BorderThickness = 1;
            this.Settings_dash.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(114)))), ((int)(((byte)(30)))));
            this.Settings_dash.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.Settings_dash.onHoverState.IconLeftImage = null;
            this.Settings_dash.onHoverState.IconRightImage = null;
            this.Settings_dash.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.Settings_dash.OnIdleState.BorderRadius = 10;
            this.Settings_dash.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Settings_dash.OnIdleState.BorderThickness = 1;
            this.Settings_dash.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.Settings_dash.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.Settings_dash.OnIdleState.IconLeftImage = null;
            this.Settings_dash.OnIdleState.IconRightImage = null;
            this.Settings_dash.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(114)))), ((int)(((byte)(30)))));
            this.Settings_dash.OnPressedState.BorderRadius = 10;
            this.Settings_dash.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Settings_dash.OnPressedState.BorderThickness = 1;
            this.Settings_dash.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(114)))), ((int)(((byte)(30)))));
            this.Settings_dash.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.Settings_dash.OnPressedState.IconLeftImage = null;
            this.Settings_dash.OnPressedState.IconRightImage = null;
            this.Settings_dash.Size = new System.Drawing.Size(76, 21);
            this.Settings_dash.TabIndex = 49;
            this.Settings_dash.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Settings_dash.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Settings_dash.TextMarginLeft = 0;
            this.Settings_dash.TextPadding = new System.Windows.Forms.Padding(0);
            this.Settings_dash.UseDefaultRadiusAndThickness = true;
            this.Settings_dash.Click += new System.EventHandler(this.bunifuButton7_Click);
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel3.ForeColor = System.Drawing.SystemColors.ButtonHighlight;
            this.bunifuLabel3.Location = new System.Drawing.Point(97, 4);
            this.bunifuLabel3.Margin = new System.Windows.Forms.Padding(4);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(104, 28);
            this.bunifuLabel3.TabIndex = 3;
            this.bunifuLabel3.Text = "User Name";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuLabel3.Click += new System.EventHandler(this.bunifuLabel3_Click);
            // 
            // OrderHistory_dash
            // 
            this.OrderHistory_dash.AllowAnimations = true;
            this.OrderHistory_dash.AllowMouseEffects = true;
            this.OrderHistory_dash.AllowToggling = true;
            this.OrderHistory_dash.AnimationSpeed = 200;
            this.OrderHistory_dash.AutoGenerateColors = false;
            this.OrderHistory_dash.AutoRoundBorders = false;
            this.OrderHistory_dash.AutoSizeLeftIcon = true;
            this.OrderHistory_dash.AutoSizeRightIcon = true;
            this.OrderHistory_dash.BackColor = System.Drawing.Color.Transparent;
            this.OrderHistory_dash.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.OrderHistory_dash.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("OrderHistory_dash.BackgroundImage")));
            this.OrderHistory_dash.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.OrderHistory_dash.ButtonText = "         ORDER HISTORY";
            this.OrderHistory_dash.ButtonTextMarginLeft = 0;
            this.OrderHistory_dash.ColorContrastOnClick = 45;
            this.OrderHistory_dash.ColorContrastOnHover = 45;
            this.OrderHistory_dash.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.OrderHistory_dash.CustomizableEdges = borderEdges3;
            this.OrderHistory_dash.DialogResult = System.Windows.Forms.DialogResult.None;
            this.OrderHistory_dash.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.OrderHistory_dash.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.OrderHistory_dash.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.OrderHistory_dash.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.OrderHistory_dash.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.OrderHistory_dash.ForeColor = System.Drawing.Color.Black;
            this.OrderHistory_dash.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.OrderHistory_dash.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.OrderHistory_dash.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.OrderHistory_dash.IconMarginLeft = 11;
            this.OrderHistory_dash.IconPadding = 10;
            this.OrderHistory_dash.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.OrderHistory_dash.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.OrderHistory_dash.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.OrderHistory_dash.IconSize = 25;
            this.OrderHistory_dash.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.OrderHistory_dash.IdleBorderRadius = 20;
            this.OrderHistory_dash.IdleBorderThickness = 1;
            this.OrderHistory_dash.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.OrderHistory_dash.IdleIconLeftImage = global::WindowsFormsApp3.Properties.Resources.file;
            this.OrderHistory_dash.IdleIconRightImage = null;
            this.OrderHistory_dash.IndicateFocus = true;
            this.OrderHistory_dash.Location = new System.Drawing.Point(7, 400);
            this.OrderHistory_dash.Margin = new System.Windows.Forms.Padding(4);
            this.OrderHistory_dash.Name = "OrderHistory_dash";
            this.OrderHistory_dash.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.OrderHistory_dash.OnDisabledState.BorderRadius = 20;
            this.OrderHistory_dash.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.OrderHistory_dash.OnDisabledState.BorderThickness = 1;
            this.OrderHistory_dash.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.OrderHistory_dash.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.OrderHistory_dash.OnDisabledState.IconLeftImage = null;
            this.OrderHistory_dash.OnDisabledState.IconRightImage = null;
            this.OrderHistory_dash.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(114)))), ((int)(((byte)(30)))));
            this.OrderHistory_dash.onHoverState.BorderRadius = 20;
            this.OrderHistory_dash.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.OrderHistory_dash.onHoverState.BorderThickness = 1;
            this.OrderHistory_dash.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(114)))), ((int)(((byte)(30)))));
            this.OrderHistory_dash.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.OrderHistory_dash.onHoverState.IconLeftImage = null;
            this.OrderHistory_dash.onHoverState.IconRightImage = null;
            this.OrderHistory_dash.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.OrderHistory_dash.OnIdleState.BorderRadius = 20;
            this.OrderHistory_dash.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.OrderHistory_dash.OnIdleState.BorderThickness = 1;
            this.OrderHistory_dash.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.OrderHistory_dash.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.OrderHistory_dash.OnIdleState.IconLeftImage = global::WindowsFormsApp3.Properties.Resources.file;
            this.OrderHistory_dash.OnIdleState.IconRightImage = null;
            this.OrderHistory_dash.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(114)))), ((int)(((byte)(30)))));
            this.OrderHistory_dash.OnPressedState.BorderRadius = 20;
            this.OrderHistory_dash.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.OrderHistory_dash.OnPressedState.BorderThickness = 1;
            this.OrderHistory_dash.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(114)))), ((int)(((byte)(30)))));
            this.OrderHistory_dash.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.OrderHistory_dash.OnPressedState.IconLeftImage = null;
            this.OrderHistory_dash.OnPressedState.IconRightImage = null;
            this.OrderHistory_dash.Size = new System.Drawing.Size(241, 48);
            this.OrderHistory_dash.TabIndex = 47;
            this.OrderHistory_dash.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.OrderHistory_dash.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.OrderHistory_dash.TextMarginLeft = 0;
            this.OrderHistory_dash.TextPadding = new System.Windows.Forms.Padding(0);
            this.OrderHistory_dash.UseDefaultRadiusAndThickness = true;
            this.OrderHistory_dash.Click += new System.EventHandler(this.OrderHistory_dash_Click);
            // 
            // Order_dash
            // 
            this.Order_dash.AllowAnimations = true;
            this.Order_dash.AllowMouseEffects = true;
            this.Order_dash.AllowToggling = true;
            this.Order_dash.AnimationSpeed = 200;
            this.Order_dash.AutoGenerateColors = false;
            this.Order_dash.AutoRoundBorders = false;
            this.Order_dash.AutoSizeLeftIcon = true;
            this.Order_dash.AutoSizeRightIcon = true;
            this.Order_dash.BackColor = System.Drawing.Color.Transparent;
            this.Order_dash.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.Order_dash.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Order_dash.BackgroundImage")));
            this.Order_dash.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Order_dash.ButtonText = "         ORDERS";
            this.Order_dash.ButtonTextMarginLeft = 0;
            this.Order_dash.ColorContrastOnClick = 45;
            this.Order_dash.ColorContrastOnHover = 45;
            this.Order_dash.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.Order_dash.CustomizableEdges = borderEdges4;
            this.Order_dash.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Order_dash.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Order_dash.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Order_dash.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Order_dash.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Order_dash.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Order_dash.ForeColor = System.Drawing.Color.Black;
            this.Order_dash.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Order_dash.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Order_dash.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Order_dash.IconMarginLeft = 11;
            this.Order_dash.IconPadding = 10;
            this.Order_dash.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Order_dash.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Order_dash.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Order_dash.IconSize = 25;
            this.Order_dash.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.Order_dash.IdleBorderRadius = 20;
            this.Order_dash.IdleBorderThickness = 1;
            this.Order_dash.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.Order_dash.IdleIconLeftImage = global::WindowsFormsApp3.Properties.Resources.checklist;
            this.Order_dash.IdleIconRightImage = null;
            this.Order_dash.IndicateFocus = true;
            this.Order_dash.Location = new System.Drawing.Point(7, 345);
            this.Order_dash.Margin = new System.Windows.Forms.Padding(4);
            this.Order_dash.Name = "Order_dash";
            this.Order_dash.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Order_dash.OnDisabledState.BorderRadius = 20;
            this.Order_dash.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Order_dash.OnDisabledState.BorderThickness = 1;
            this.Order_dash.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Order_dash.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Order_dash.OnDisabledState.IconLeftImage = null;
            this.Order_dash.OnDisabledState.IconRightImage = null;
            this.Order_dash.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(114)))), ((int)(((byte)(30)))));
            this.Order_dash.onHoverState.BorderRadius = 20;
            this.Order_dash.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Order_dash.onHoverState.BorderThickness = 1;
            this.Order_dash.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(114)))), ((int)(((byte)(30)))));
            this.Order_dash.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.Order_dash.onHoverState.IconLeftImage = null;
            this.Order_dash.onHoverState.IconRightImage = null;
            this.Order_dash.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.Order_dash.OnIdleState.BorderRadius = 20;
            this.Order_dash.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Order_dash.OnIdleState.BorderThickness = 1;
            this.Order_dash.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.Order_dash.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.Order_dash.OnIdleState.IconLeftImage = global::WindowsFormsApp3.Properties.Resources.checklist;
            this.Order_dash.OnIdleState.IconRightImage = null;
            this.Order_dash.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(114)))), ((int)(((byte)(30)))));
            this.Order_dash.OnPressedState.BorderRadius = 20;
            this.Order_dash.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Order_dash.OnPressedState.BorderThickness = 1;
            this.Order_dash.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(114)))), ((int)(((byte)(30)))));
            this.Order_dash.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.Order_dash.OnPressedState.IconLeftImage = null;
            this.Order_dash.OnPressedState.IconRightImage = null;
            this.Order_dash.Size = new System.Drawing.Size(241, 48);
            this.Order_dash.TabIndex = 46;
            this.Order_dash.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Order_dash.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Order_dash.TextMarginLeft = 0;
            this.Order_dash.TextPadding = new System.Windows.Forms.Padding(0);
            this.Order_dash.UseDefaultRadiusAndThickness = true;
            this.Order_dash.Click += new System.EventHandler(this.Order_dash_Click);
            // 
            // Customer_dash
            // 
            this.Customer_dash.AllowAnimations = true;
            this.Customer_dash.AllowMouseEffects = true;
            this.Customer_dash.AllowToggling = true;
            this.Customer_dash.AnimationSpeed = 200;
            this.Customer_dash.AutoGenerateColors = false;
            this.Customer_dash.AutoRoundBorders = false;
            this.Customer_dash.AutoSizeLeftIcon = true;
            this.Customer_dash.AutoSizeRightIcon = true;
            this.Customer_dash.BackColor = System.Drawing.Color.Transparent;
            this.Customer_dash.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.Customer_dash.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Customer_dash.BackgroundImage")));
            this.Customer_dash.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Customer_dash.ButtonText = "         CUSTOMER";
            this.Customer_dash.ButtonTextMarginLeft = 0;
            this.Customer_dash.ColorContrastOnClick = 45;
            this.Customer_dash.ColorContrastOnHover = 45;
            this.Customer_dash.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.Customer_dash.CustomizableEdges = borderEdges5;
            this.Customer_dash.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Customer_dash.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Customer_dash.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Customer_dash.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Customer_dash.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Customer_dash.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Customer_dash.ForeColor = System.Drawing.Color.Black;
            this.Customer_dash.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Customer_dash.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Customer_dash.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Customer_dash.IconMarginLeft = 11;
            this.Customer_dash.IconPadding = 10;
            this.Customer_dash.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Customer_dash.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Customer_dash.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Customer_dash.IconSize = 25;
            this.Customer_dash.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.Customer_dash.IdleBorderRadius = 20;
            this.Customer_dash.IdleBorderThickness = 1;
            this.Customer_dash.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.Customer_dash.IdleIconLeftImage = global::WindowsFormsApp3.Properties.Resources.customer;
            this.Customer_dash.IdleIconRightImage = null;
            this.Customer_dash.IndicateFocus = true;
            this.Customer_dash.Location = new System.Drawing.Point(7, 289);
            this.Customer_dash.Margin = new System.Windows.Forms.Padding(4);
            this.Customer_dash.Name = "Customer_dash";
            this.Customer_dash.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Customer_dash.OnDisabledState.BorderRadius = 20;
            this.Customer_dash.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Customer_dash.OnDisabledState.BorderThickness = 1;
            this.Customer_dash.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Customer_dash.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Customer_dash.OnDisabledState.IconLeftImage = null;
            this.Customer_dash.OnDisabledState.IconRightImage = null;
            this.Customer_dash.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(114)))), ((int)(((byte)(30)))));
            this.Customer_dash.onHoverState.BorderRadius = 20;
            this.Customer_dash.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Customer_dash.onHoverState.BorderThickness = 1;
            this.Customer_dash.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(114)))), ((int)(((byte)(30)))));
            this.Customer_dash.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.Customer_dash.onHoverState.IconLeftImage = null;
            this.Customer_dash.onHoverState.IconRightImage = null;
            this.Customer_dash.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.Customer_dash.OnIdleState.BorderRadius = 20;
            this.Customer_dash.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Customer_dash.OnIdleState.BorderThickness = 1;
            this.Customer_dash.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.Customer_dash.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.Customer_dash.OnIdleState.IconLeftImage = global::WindowsFormsApp3.Properties.Resources.customer;
            this.Customer_dash.OnIdleState.IconRightImage = null;
            this.Customer_dash.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(114)))), ((int)(((byte)(30)))));
            this.Customer_dash.OnPressedState.BorderRadius = 20;
            this.Customer_dash.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Customer_dash.OnPressedState.BorderThickness = 1;
            this.Customer_dash.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(114)))), ((int)(((byte)(30)))));
            this.Customer_dash.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.Customer_dash.OnPressedState.IconLeftImage = null;
            this.Customer_dash.OnPressedState.IconRightImage = null;
            this.Customer_dash.Size = new System.Drawing.Size(241, 48);
            this.Customer_dash.TabIndex = 45;
            this.Customer_dash.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Customer_dash.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Customer_dash.TextMarginLeft = 0;
            this.Customer_dash.TextPadding = new System.Windows.Forms.Padding(0);
            this.Customer_dash.UseDefaultRadiusAndThickness = true;
            this.Customer_dash.Click += new System.EventHandler(this.Customer_dash_Click);
            // 
            // Products_dash
            // 
            this.Products_dash.AllowAnimations = true;
            this.Products_dash.AllowMouseEffects = true;
            this.Products_dash.AllowToggling = true;
            this.Products_dash.AnimationSpeed = 200;
            this.Products_dash.AutoGenerateColors = false;
            this.Products_dash.AutoRoundBorders = false;
            this.Products_dash.AutoSizeLeftIcon = true;
            this.Products_dash.AutoSizeRightIcon = true;
            this.Products_dash.BackColor = System.Drawing.Color.Transparent;
            this.Products_dash.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.Products_dash.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Products_dash.BackgroundImage")));
            this.Products_dash.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Products_dash.ButtonText = "         PRODUCTS";
            this.Products_dash.ButtonTextMarginLeft = 0;
            this.Products_dash.ColorContrastOnClick = 45;
            this.Products_dash.ColorContrastOnHover = 45;
            this.Products_dash.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.Products_dash.CustomizableEdges = borderEdges6;
            this.Products_dash.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Products_dash.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Products_dash.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Products_dash.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Products_dash.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Products_dash.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Products_dash.ForeColor = System.Drawing.Color.Black;
            this.Products_dash.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Products_dash.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Products_dash.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Products_dash.IconMarginLeft = 11;
            this.Products_dash.IconPadding = 10;
            this.Products_dash.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Products_dash.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Products_dash.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Products_dash.IconSize = 25;
            this.Products_dash.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.Products_dash.IdleBorderRadius = 20;
            this.Products_dash.IdleBorderThickness = 1;
            this.Products_dash.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.Products_dash.IdleIconLeftImage = global::WindowsFormsApp3.Properties.Resources.package;
            this.Products_dash.IdleIconRightImage = null;
            this.Products_dash.IndicateFocus = true;
            this.Products_dash.Location = new System.Drawing.Point(7, 234);
            this.Products_dash.Margin = new System.Windows.Forms.Padding(4);
            this.Products_dash.Name = "Products_dash";
            this.Products_dash.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Products_dash.OnDisabledState.BorderRadius = 20;
            this.Products_dash.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Products_dash.OnDisabledState.BorderThickness = 1;
            this.Products_dash.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Products_dash.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Products_dash.OnDisabledState.IconLeftImage = null;
            this.Products_dash.OnDisabledState.IconRightImage = null;
            this.Products_dash.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(114)))), ((int)(((byte)(30)))));
            this.Products_dash.onHoverState.BorderRadius = 20;
            this.Products_dash.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Products_dash.onHoverState.BorderThickness = 1;
            this.Products_dash.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(114)))), ((int)(((byte)(30)))));
            this.Products_dash.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.Products_dash.onHoverState.IconLeftImage = null;
            this.Products_dash.onHoverState.IconRightImage = null;
            this.Products_dash.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.Products_dash.OnIdleState.BorderRadius = 20;
            this.Products_dash.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Products_dash.OnIdleState.BorderThickness = 1;
            this.Products_dash.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.Products_dash.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.Products_dash.OnIdleState.IconLeftImage = global::WindowsFormsApp3.Properties.Resources.package;
            this.Products_dash.OnIdleState.IconRightImage = null;
            this.Products_dash.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(114)))), ((int)(((byte)(30)))));
            this.Products_dash.OnPressedState.BorderRadius = 20;
            this.Products_dash.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Products_dash.OnPressedState.BorderThickness = 1;
            this.Products_dash.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(114)))), ((int)(((byte)(30)))));
            this.Products_dash.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.Products_dash.OnPressedState.IconLeftImage = null;
            this.Products_dash.OnPressedState.IconRightImage = null;
            this.Products_dash.Size = new System.Drawing.Size(241, 48);
            this.Products_dash.TabIndex = 44;
            this.Products_dash.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Products_dash.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Products_dash.TextMarginLeft = 0;
            this.Products_dash.TextPadding = new System.Windows.Forms.Padding(0);
            this.Products_dash.UseDefaultRadiusAndThickness = true;
            this.Products_dash.Click += new System.EventHandler(this.Products_dash_Click);
            // 
            // Category_dash
            // 
            this.Category_dash.AllowAnimations = true;
            this.Category_dash.AllowMouseEffects = true;
            this.Category_dash.AllowToggling = true;
            this.Category_dash.AnimationSpeed = 200;
            this.Category_dash.AutoGenerateColors = false;
            this.Category_dash.AutoRoundBorders = false;
            this.Category_dash.AutoSizeLeftIcon = true;
            this.Category_dash.AutoSizeRightIcon = true;
            this.Category_dash.BackColor = System.Drawing.Color.Transparent;
            this.Category_dash.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.Category_dash.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Category_dash.BackgroundImage")));
            this.Category_dash.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Category_dash.ButtonText = "         CETEGORY";
            this.Category_dash.ButtonTextMarginLeft = 0;
            this.Category_dash.ColorContrastOnClick = 45;
            this.Category_dash.ColorContrastOnHover = 45;
            this.Category_dash.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.Category_dash.CustomizableEdges = borderEdges7;
            this.Category_dash.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Category_dash.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Category_dash.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Category_dash.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Category_dash.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Category_dash.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Category_dash.ForeColor = System.Drawing.Color.Black;
            this.Category_dash.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Category_dash.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Category_dash.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Category_dash.IconMarginLeft = 11;
            this.Category_dash.IconPadding = 10;
            this.Category_dash.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Category_dash.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Category_dash.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Category_dash.IconSize = 25;
            this.Category_dash.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.Category_dash.IdleBorderRadius = 20;
            this.Category_dash.IdleBorderThickness = 1;
            this.Category_dash.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.Category_dash.IdleIconLeftImage = global::WindowsFormsApp3.Properties.Resources.menu;
            this.Category_dash.IdleIconRightImage = null;
            this.Category_dash.IndicateFocus = true;
            this.Category_dash.Location = new System.Drawing.Point(7, 178);
            this.Category_dash.Margin = new System.Windows.Forms.Padding(4);
            this.Category_dash.Name = "Category_dash";
            this.Category_dash.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Category_dash.OnDisabledState.BorderRadius = 20;
            this.Category_dash.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Category_dash.OnDisabledState.BorderThickness = 1;
            this.Category_dash.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Category_dash.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Category_dash.OnDisabledState.IconLeftImage = null;
            this.Category_dash.OnDisabledState.IconRightImage = null;
            this.Category_dash.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(114)))), ((int)(((byte)(30)))));
            this.Category_dash.onHoverState.BorderRadius = 20;
            this.Category_dash.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Category_dash.onHoverState.BorderThickness = 1;
            this.Category_dash.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(114)))), ((int)(((byte)(30)))));
            this.Category_dash.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.Category_dash.onHoverState.IconLeftImage = null;
            this.Category_dash.onHoverState.IconRightImage = null;
            this.Category_dash.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.Category_dash.OnIdleState.BorderRadius = 20;
            this.Category_dash.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Category_dash.OnIdleState.BorderThickness = 1;
            this.Category_dash.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.Category_dash.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.Category_dash.OnIdleState.IconLeftImage = global::WindowsFormsApp3.Properties.Resources.menu;
            this.Category_dash.OnIdleState.IconRightImage = null;
            this.Category_dash.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(114)))), ((int)(((byte)(30)))));
            this.Category_dash.OnPressedState.BorderRadius = 20;
            this.Category_dash.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Category_dash.OnPressedState.BorderThickness = 1;
            this.Category_dash.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(114)))), ((int)(((byte)(30)))));
            this.Category_dash.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.Category_dash.OnPressedState.IconLeftImage = null;
            this.Category_dash.OnPressedState.IconRightImage = null;
            this.Category_dash.Size = new System.Drawing.Size(241, 48);
            this.Category_dash.TabIndex = 43;
            this.Category_dash.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Category_dash.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Category_dash.TextMarginLeft = 0;
            this.Category_dash.TextPadding = new System.Windows.Forms.Padding(0);
            this.Category_dash.UseDefaultRadiusAndThickness = true;
            this.Category_dash.Click += new System.EventHandler(this.Category_dash_Click_1);
            // 
            // Dashboard_dash
            // 
            this.Dashboard_dash.AllowAnimations = true;
            this.Dashboard_dash.AllowMouseEffects = true;
            this.Dashboard_dash.AllowToggling = true;
            this.Dashboard_dash.AnimationSpeed = 200;
            this.Dashboard_dash.AutoGenerateColors = false;
            this.Dashboard_dash.AutoRoundBorders = false;
            this.Dashboard_dash.AutoSizeLeftIcon = true;
            this.Dashboard_dash.AutoSizeRightIcon = true;
            this.Dashboard_dash.BackColor = System.Drawing.Color.Transparent;
            this.Dashboard_dash.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.Dashboard_dash.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Dashboard_dash.BackgroundImage")));
            this.Dashboard_dash.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Dashboard_dash.ButtonText = "DASHBOARD";
            this.Dashboard_dash.ButtonTextMarginLeft = 0;
            this.Dashboard_dash.ColorContrastOnClick = 45;
            this.Dashboard_dash.ColorContrastOnHover = 45;
            this.Dashboard_dash.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.Dashboard_dash.CustomizableEdges = borderEdges8;
            this.Dashboard_dash.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Dashboard_dash.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Dashboard_dash.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Dashboard_dash.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Dashboard_dash.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Dashboard_dash.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Dashboard_dash.ForeColor = System.Drawing.Color.Black;
            this.Dashboard_dash.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Dashboard_dash.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Dashboard_dash.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Dashboard_dash.IconMarginLeft = 11;
            this.Dashboard_dash.IconPadding = 10;
            this.Dashboard_dash.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Dashboard_dash.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Dashboard_dash.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Dashboard_dash.IconSize = 25;
            this.Dashboard_dash.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.Dashboard_dash.IdleBorderRadius = 20;
            this.Dashboard_dash.IdleBorderThickness = 1;
            this.Dashboard_dash.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.Dashboard_dash.IdleIconLeftImage = global::WindowsFormsApp3.Properties.Resources.dashboardblack1;
            this.Dashboard_dash.IdleIconRightImage = null;
            this.Dashboard_dash.IndicateFocus = true;
            this.Dashboard_dash.Location = new System.Drawing.Point(7, 123);
            this.Dashboard_dash.Margin = new System.Windows.Forms.Padding(4);
            this.Dashboard_dash.Name = "Dashboard_dash";
            this.Dashboard_dash.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Dashboard_dash.OnDisabledState.BorderRadius = 20;
            this.Dashboard_dash.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Dashboard_dash.OnDisabledState.BorderThickness = 1;
            this.Dashboard_dash.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Dashboard_dash.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Dashboard_dash.OnDisabledState.IconLeftImage = null;
            this.Dashboard_dash.OnDisabledState.IconRightImage = null;
            this.Dashboard_dash.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(114)))), ((int)(((byte)(30)))));
            this.Dashboard_dash.onHoverState.BorderRadius = 20;
            this.Dashboard_dash.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Dashboard_dash.onHoverState.BorderThickness = 1;
            this.Dashboard_dash.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(114)))), ((int)(((byte)(30)))));
            this.Dashboard_dash.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.Dashboard_dash.onHoverState.IconLeftImage = null;
            this.Dashboard_dash.onHoverState.IconRightImage = null;
            this.Dashboard_dash.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.Dashboard_dash.OnIdleState.BorderRadius = 20;
            this.Dashboard_dash.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Dashboard_dash.OnIdleState.BorderThickness = 1;
            this.Dashboard_dash.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.Dashboard_dash.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.Dashboard_dash.OnIdleState.IconLeftImage = global::WindowsFormsApp3.Properties.Resources.dashboardblack1;
            this.Dashboard_dash.OnIdleState.IconRightImage = null;
            this.Dashboard_dash.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(114)))), ((int)(((byte)(30)))));
            this.Dashboard_dash.OnPressedState.BorderRadius = 20;
            this.Dashboard_dash.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Dashboard_dash.OnPressedState.BorderThickness = 1;
            this.Dashboard_dash.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(114)))), ((int)(((byte)(30)))));
            this.Dashboard_dash.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.Dashboard_dash.OnPressedState.IconLeftImage = null;
            this.Dashboard_dash.OnPressedState.IconRightImage = null;
            this.Dashboard_dash.Size = new System.Drawing.Size(241, 48);
            this.Dashboard_dash.TabIndex = 42;
            this.Dashboard_dash.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Dashboard_dash.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Dashboard_dash.TextMarginLeft = 0;
            this.Dashboard_dash.TextPadding = new System.Windows.Forms.Padding(0);
            this.Dashboard_dash.UseDefaultRadiusAndThickness = true;
            this.Dashboard_dash.Click += new System.EventHandler(this.Dashboard_dash_Click_1);
            // 
            // Dashboard
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.AutoSize = true;
            this.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(32)))), ((int)(((byte)(13)))), ((int)(((byte)(51)))));
            this.ClientSize = new System.Drawing.Size(1683, 828);
            this.Controls.Add(this.bunifuPanel5);
            this.Controls.Add(this.bunifuPanel6);
            this.Controls.Add(this.bunifuPanel1);
            this.ForeColor = System.Drawing.SystemColors.ControlText;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Margin = new System.Windows.Forms.Padding(4);
            this.MaximumSize = new System.Drawing.Size(1701, 875);
            this.MinimumSize = new System.Drawing.Size(1701, 875);
            this.Name = "Dashboard";
            this.Palette = this.kryptonPalette1;
            this.PaletteMode = ComponentFactory.Krypton.Toolkit.PaletteMode.Custom;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Load += new System.EventHandler(this.Navi_Load);
            this.bunifuPanel5.ResumeLayout(false);
            this.bunifuPanel6.ResumeLayout(false);
            this.bunifuPanel2.ResumeLayout(false);
            this.bunifuPanel4.ResumeLayout(false);
            this.bunifuPanel4.PerformLayout();
            this.bunifuPanel3.ResumeLayout(false);
            this.bunifuPanel3.PerformLayout();
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private ComponentFactory.Krypton.Toolkit.KryptonPalette kryptonPalette1;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Dashboard_dash;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton OrderHistory_dash;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Order_dash;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Customer_dash;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Products_dash;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Category_dash;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Exit_dash;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Settings_dash;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private System.Windows.Forms.PictureBox pictureBox1;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel3;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel4;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel2;
        private Bunifu.UI.WinForms.BunifuDatePicker Date_dash;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel6;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel5;
        private Dashboard_UC dashboard_UC1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label3;
    }
}