namespace WindowsFormsApp3
{
    partial class sub_products
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(sub_products));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.kryptonPalette1 = new ComponentFactory.Krypton.Toolkit.KryptonPalette(this.components);
            this.product_id = new Bunifu.UI.WinForms.BunifuTextBox();
            this.product_name = new Bunifu.UI.WinForms.BunifuTextBox();
            this.product_qty = new Bunifu.UI.WinForms.BunifuTextBox();
            this.product_price = new Bunifu.UI.WinForms.BunifuTextBox();
            this.product_category = new Bunifu.UI.WinForms.BunifuDropdown();
            this.label1 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.productdeletebutton2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.productupdatebutton3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.productinsertbutton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuDataGridView1 = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.label6 = new System.Windows.Forms.Label();
            this.categorydropdownsearchbar1 = new Bunifu.UI.WinForms.BunifuDropdown();
            this.label7 = new System.Windows.Forms.Label();
            this.bunifuPanel2 = new Bunifu.UI.WinForms.BunifuPanel();
            this.productsearchbutton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.refreshbutton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuDataGridView1)).BeginInit();
            this.bunifuPanel2.SuspendLayout();
            this.SuspendLayout();
            // 
            // kryptonPalette1
            // 
            this.kryptonPalette1.ButtonSpecs.FormClose.Image = ((System.Drawing.Image)(resources.GetObject("kryptonPalette1.ButtonSpecs.FormClose.Image")));
            this.kryptonPalette1.ButtonSpecs.FormClose.ImageStates.ImagePressed = ((System.Drawing.Image)(resources.GetObject("kryptonPalette1.ButtonSpecs.FormClose.ImageStates.ImagePressed")));
            this.kryptonPalette1.ButtonSpecs.FormClose.ImageStates.ImageTracking = ((System.Drawing.Image)(resources.GetObject("kryptonPalette1.ButtonSpecs.FormClose.ImageStates.ImageTracking")));
            this.kryptonPalette1.ButtonSpecs.FormMax.Image = ((System.Drawing.Image)(resources.GetObject("kryptonPalette1.ButtonSpecs.FormMax.Image")));
            this.kryptonPalette1.ButtonSpecs.FormMax.ImageStates.ImageCheckedPressed = ((System.Drawing.Image)(resources.GetObject("kryptonPalette1.ButtonSpecs.FormMax.ImageStates.ImageCheckedPressed")));
            this.kryptonPalette1.ButtonSpecs.FormMax.ImageStates.ImagePressed = ((System.Drawing.Image)(resources.GetObject("kryptonPalette1.ButtonSpecs.FormMax.ImageStates.ImagePressed")));
            this.kryptonPalette1.ButtonSpecs.FormMax.ImageStates.ImageTracking = ((System.Drawing.Image)(resources.GetObject("kryptonPalette1.ButtonSpecs.FormMax.ImageStates.ImageTracking")));
            this.kryptonPalette1.ButtonSpecs.FormMin.Image = ((System.Drawing.Image)(resources.GetObject("kryptonPalette1.ButtonSpecs.FormMin.Image")));
            this.kryptonPalette1.ButtonSpecs.FormMin.ImageStates.ImagePressed = ((System.Drawing.Image)(resources.GetObject("kryptonPalette1.ButtonSpecs.FormMin.ImageStates.ImagePressed")));
            this.kryptonPalette1.ButtonSpecs.FormMin.ImageStates.ImageTracking = ((System.Drawing.Image)(resources.GetObject("kryptonPalette1.ButtonSpecs.FormMin.ImageStates.ImageTracking")));
            this.kryptonPalette1.ButtonStyles.ButtonForm.StateNormal.Back.Color1 = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(252)))), ((int)(((byte)(252)))));
            this.kryptonPalette1.ButtonStyles.ButtonForm.StateNormal.Back.Color2 = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(252)))), ((int)(((byte)(252)))));
            this.kryptonPalette1.ButtonStyles.ButtonForm.StateNormal.Border.DrawBorders = ((ComponentFactory.Krypton.Toolkit.PaletteDrawBorders)((((ComponentFactory.Krypton.Toolkit.PaletteDrawBorders.Top | ComponentFactory.Krypton.Toolkit.PaletteDrawBorders.Bottom) 
            | ComponentFactory.Krypton.Toolkit.PaletteDrawBorders.Left) 
            | ComponentFactory.Krypton.Toolkit.PaletteDrawBorders.Right)));
            this.kryptonPalette1.ButtonStyles.ButtonForm.StateNormal.Border.Width = 0;
            this.kryptonPalette1.ButtonStyles.ButtonForm.StatePressed.Back.Color1 = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(252)))), ((int)(((byte)(252)))));
            this.kryptonPalette1.ButtonStyles.ButtonForm.StatePressed.Back.Color2 = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(252)))), ((int)(((byte)(252)))));
            this.kryptonPalette1.ButtonStyles.ButtonForm.StatePressed.Border.DrawBorders = ((ComponentFactory.Krypton.Toolkit.PaletteDrawBorders)((((ComponentFactory.Krypton.Toolkit.PaletteDrawBorders.Top | ComponentFactory.Krypton.Toolkit.PaletteDrawBorders.Bottom) 
            | ComponentFactory.Krypton.Toolkit.PaletteDrawBorders.Left) 
            | ComponentFactory.Krypton.Toolkit.PaletteDrawBorders.Right)));
            this.kryptonPalette1.ButtonStyles.ButtonForm.StatePressed.Border.Width = 0;
            this.kryptonPalette1.ButtonStyles.ButtonForm.StateTracking.Back.Color1 = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(252)))), ((int)(((byte)(252)))));
            this.kryptonPalette1.ButtonStyles.ButtonForm.StateTracking.Back.Color2 = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(252)))), ((int)(((byte)(252)))));
            this.kryptonPalette1.ButtonStyles.ButtonForm.StateTracking.Border.DrawBorders = ((ComponentFactory.Krypton.Toolkit.PaletteDrawBorders)((((ComponentFactory.Krypton.Toolkit.PaletteDrawBorders.Top | ComponentFactory.Krypton.Toolkit.PaletteDrawBorders.Bottom) 
            | ComponentFactory.Krypton.Toolkit.PaletteDrawBorders.Left) 
            | ComponentFactory.Krypton.Toolkit.PaletteDrawBorders.Right)));
            this.kryptonPalette1.ButtonStyles.ButtonForm.StateTracking.Border.Width = 0;
            this.kryptonPalette1.FormStyles.FormCommon.StateCommon.Back.Color1 = System.Drawing.Color.FromArgb(((int)(((byte)(32)))), ((int)(((byte)(13)))), ((int)(((byte)(51)))));
            this.kryptonPalette1.FormStyles.FormCommon.StateCommon.Back.Color2 = System.Drawing.Color.FromArgb(((int)(((byte)(32)))), ((int)(((byte)(13)))), ((int)(((byte)(51)))));
            this.kryptonPalette1.FormStyles.FormCommon.StateCommon.Border.DrawBorders = ((ComponentFactory.Krypton.Toolkit.PaletteDrawBorders)((((ComponentFactory.Krypton.Toolkit.PaletteDrawBorders.Top | ComponentFactory.Krypton.Toolkit.PaletteDrawBorders.Bottom) 
            | ComponentFactory.Krypton.Toolkit.PaletteDrawBorders.Left) 
            | ComponentFactory.Krypton.Toolkit.PaletteDrawBorders.Right)));
            this.kryptonPalette1.FormStyles.FormCommon.StateCommon.Border.GraphicsHint = ComponentFactory.Krypton.Toolkit.PaletteGraphicsHint.None;
            this.kryptonPalette1.FormStyles.FormCommon.StateCommon.Border.Rounding = 10;
            this.kryptonPalette1.HeaderStyles.HeaderForm.StateCommon.Back.Color1 = System.Drawing.Color.FromArgb(((int)(((byte)(32)))), ((int)(((byte)(13)))), ((int)(((byte)(51)))));
            this.kryptonPalette1.HeaderStyles.HeaderForm.StateCommon.Back.Color2 = System.Drawing.Color.FromArgb(((int)(((byte)(32)))), ((int)(((byte)(13)))), ((int)(((byte)(51)))));
            this.kryptonPalette1.HeaderStyles.HeaderForm.StateCommon.Content.Padding = new System.Windows.Forms.Padding(10, -1, -1, -1);
            // 
            // product_id
            // 
            this.product_id.AcceptsReturn = false;
            this.product_id.AcceptsTab = false;
            this.product_id.AnimationSpeed = 200;
            this.product_id.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.product_id.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.product_id.BackColor = System.Drawing.Color.Transparent;
            this.product_id.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("product_id.BackgroundImage")));
            this.product_id.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.product_id.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.product_id.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.product_id.BorderColorIdle = System.Drawing.Color.Silver;
            this.product_id.BorderRadius = 20;
            this.product_id.BorderThickness = 1;
            this.product_id.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.product_id.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.product_id.DefaultFont = new System.Drawing.Font("Segoe UI", 11.25F);
            this.product_id.DefaultText = "";
            this.product_id.FillColor = System.Drawing.Color.White;
            this.product_id.HideSelection = true;
            this.product_id.IconLeft = null;
            this.product_id.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.product_id.IconPadding = 10;
            this.product_id.IconRight = null;
            this.product_id.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.product_id.Lines = new string[0];
            this.product_id.Location = new System.Drawing.Point(328, 38);
            this.product_id.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.product_id.MaxLength = 32767;
            this.product_id.MinimumSize = new System.Drawing.Size(1, 1);
            this.product_id.Modified = false;
            this.product_id.Multiline = false;
            this.product_id.Name = "product_id";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.product_id.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.product_id.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.product_id.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.product_id.OnIdleState = stateProperties4;
            this.product_id.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.product_id.PasswordChar = '\0';
            this.product_id.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.product_id.PlaceholderText = "Enter Product ID";
            this.product_id.ReadOnly = false;
            this.product_id.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.product_id.SelectedText = "";
            this.product_id.SelectionLength = 0;
            this.product_id.SelectionStart = 0;
            this.product_id.ShortcutsEnabled = true;
            this.product_id.Size = new System.Drawing.Size(359, 46);
            this.product_id.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.product_id.TabIndex = 67;
            this.product_id.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.product_id.TextMarginBottom = 0;
            this.product_id.TextMarginLeft = 3;
            this.product_id.TextMarginTop = 0;
            this.product_id.TextPlaceholder = "Enter Product ID";
            this.product_id.UseSystemPasswordChar = false;
            this.product_id.WordWrap = true;
            // 
            // product_name
            // 
            this.product_name.AcceptsReturn = false;
            this.product_name.AcceptsTab = false;
            this.product_name.AnimationSpeed = 200;
            this.product_name.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.product_name.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.product_name.BackColor = System.Drawing.Color.Transparent;
            this.product_name.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("product_name.BackgroundImage")));
            this.product_name.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.product_name.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.product_name.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.product_name.BorderColorIdle = System.Drawing.Color.Silver;
            this.product_name.BorderRadius = 20;
            this.product_name.BorderThickness = 1;
            this.product_name.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.product_name.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.product_name.DefaultFont = new System.Drawing.Font("Segoe UI", 11.25F);
            this.product_name.DefaultText = "";
            this.product_name.FillColor = System.Drawing.Color.White;
            this.product_name.HideSelection = true;
            this.product_name.IconLeft = null;
            this.product_name.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.product_name.IconPadding = 10;
            this.product_name.IconRight = null;
            this.product_name.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.product_name.Lines = new string[0];
            this.product_name.Location = new System.Drawing.Point(328, 95);
            this.product_name.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.product_name.MaxLength = 32767;
            this.product_name.MinimumSize = new System.Drawing.Size(1, 1);
            this.product_name.Modified = false;
            this.product_name.Multiline = false;
            this.product_name.Name = "product_name";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.product_name.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.product_name.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.product_name.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.product_name.OnIdleState = stateProperties8;
            this.product_name.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.product_name.PasswordChar = '\0';
            this.product_name.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.product_name.PlaceholderText = "Enter Product Name";
            this.product_name.ReadOnly = false;
            this.product_name.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.product_name.SelectedText = "";
            this.product_name.SelectionLength = 0;
            this.product_name.SelectionStart = 0;
            this.product_name.ShortcutsEnabled = true;
            this.product_name.Size = new System.Drawing.Size(359, 46);
            this.product_name.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.product_name.TabIndex = 66;
            this.product_name.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.product_name.TextMarginBottom = 0;
            this.product_name.TextMarginLeft = 3;
            this.product_name.TextMarginTop = 0;
            this.product_name.TextPlaceholder = "Enter Product Name";
            this.product_name.UseSystemPasswordChar = false;
            this.product_name.WordWrap = true;
            // 
            // product_qty
            // 
            this.product_qty.AcceptsReturn = false;
            this.product_qty.AcceptsTab = false;
            this.product_qty.AnimationSpeed = 200;
            this.product_qty.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.product_qty.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.product_qty.BackColor = System.Drawing.Color.Transparent;
            this.product_qty.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("product_qty.BackgroundImage")));
            this.product_qty.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.product_qty.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.product_qty.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.product_qty.BorderColorIdle = System.Drawing.Color.Silver;
            this.product_qty.BorderRadius = 20;
            this.product_qty.BorderThickness = 1;
            this.product_qty.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.product_qty.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.product_qty.DefaultFont = new System.Drawing.Font("Segoe UI", 11.25F);
            this.product_qty.DefaultText = "";
            this.product_qty.FillColor = System.Drawing.Color.White;
            this.product_qty.HideSelection = true;
            this.product_qty.IconLeft = null;
            this.product_qty.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.product_qty.IconPadding = 10;
            this.product_qty.IconRight = null;
            this.product_qty.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.product_qty.Lines = new string[0];
            this.product_qty.Location = new System.Drawing.Point(328, 153);
            this.product_qty.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.product_qty.MaxLength = 32767;
            this.product_qty.MinimumSize = new System.Drawing.Size(1, 1);
            this.product_qty.Modified = false;
            this.product_qty.Multiline = false;
            this.product_qty.Name = "product_qty";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.product_qty.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.product_qty.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.product_qty.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.product_qty.OnIdleState = stateProperties12;
            this.product_qty.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.product_qty.PasswordChar = '\0';
            this.product_qty.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.product_qty.PlaceholderText = "Enter Quantity";
            this.product_qty.ReadOnly = false;
            this.product_qty.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.product_qty.SelectedText = "";
            this.product_qty.SelectionLength = 0;
            this.product_qty.SelectionStart = 0;
            this.product_qty.ShortcutsEnabled = true;
            this.product_qty.Size = new System.Drawing.Size(359, 46);
            this.product_qty.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.product_qty.TabIndex = 65;
            this.product_qty.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.product_qty.TextMarginBottom = 0;
            this.product_qty.TextMarginLeft = 3;
            this.product_qty.TextMarginTop = 0;
            this.product_qty.TextPlaceholder = "Enter Quantity";
            this.product_qty.UseSystemPasswordChar = false;
            this.product_qty.WordWrap = true;
            // 
            // product_price
            // 
            this.product_price.AcceptsReturn = false;
            this.product_price.AcceptsTab = false;
            this.product_price.AnimationSpeed = 200;
            this.product_price.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.product_price.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.product_price.BackColor = System.Drawing.Color.Transparent;
            this.product_price.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("product_price.BackgroundImage")));
            this.product_price.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.product_price.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.product_price.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.product_price.BorderColorIdle = System.Drawing.Color.Silver;
            this.product_price.BorderRadius = 20;
            this.product_price.BorderThickness = 1;
            this.product_price.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.product_price.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.product_price.DefaultFont = new System.Drawing.Font("Segoe UI", 11.25F);
            this.product_price.DefaultText = "";
            this.product_price.FillColor = System.Drawing.Color.White;
            this.product_price.HideSelection = true;
            this.product_price.IconLeft = null;
            this.product_price.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.product_price.IconPadding = 10;
            this.product_price.IconRight = null;
            this.product_price.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.product_price.Lines = new string[0];
            this.product_price.Location = new System.Drawing.Point(328, 210);
            this.product_price.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.product_price.MaxLength = 32767;
            this.product_price.MinimumSize = new System.Drawing.Size(1, 1);
            this.product_price.Modified = false;
            this.product_price.Multiline = false;
            this.product_price.Name = "product_price";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.product_price.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.product_price.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.product_price.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.product_price.OnIdleState = stateProperties16;
            this.product_price.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.product_price.PasswordChar = '\0';
            this.product_price.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.product_price.PlaceholderText = "Enter Price";
            this.product_price.ReadOnly = false;
            this.product_price.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.product_price.SelectedText = "";
            this.product_price.SelectionLength = 0;
            this.product_price.SelectionStart = 0;
            this.product_price.ShortcutsEnabled = true;
            this.product_price.Size = new System.Drawing.Size(359, 46);
            this.product_price.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.product_price.TabIndex = 64;
            this.product_price.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.product_price.TextMarginBottom = 0;
            this.product_price.TextMarginLeft = 3;
            this.product_price.TextMarginTop = 0;
            this.product_price.TextPlaceholder = "Enter Price";
            this.product_price.UseSystemPasswordChar = false;
            this.product_price.WordWrap = true;
            // 
            // product_category
            // 
            this.product_category.AllowDrop = true;
            this.product_category.BackColor = System.Drawing.Color.Transparent;
            this.product_category.BackgroundColor = System.Drawing.Color.White;
            this.product_category.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(218)))), ((int)(((byte)(223)))));
            this.product_category.BorderRadius = 10;
            this.product_category.Color = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(218)))), ((int)(((byte)(223)))));
            this.product_category.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.product_category.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.product_category.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.product_category.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.product_category.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.product_category.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.product_category.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.product_category.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.product_category.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.product_category.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.product_category.FillDropDown = true;
            this.product_category.FillIndicator = false;
            this.product_category.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.product_category.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.product_category.ForeColor = System.Drawing.Color.Black;
            this.product_category.FormattingEnabled = true;
            this.product_category.Icon = null;
            this.product_category.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.product_category.IndicatorColor = System.Drawing.Color.Gray;
            this.product_category.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.product_category.ItemBackColor = System.Drawing.Color.White;
            this.product_category.ItemBorderColor = System.Drawing.Color.White;
            this.product_category.ItemForeColor = System.Drawing.Color.Black;
            this.product_category.ItemHeight = 35;
            this.product_category.ItemHighLightColor = System.Drawing.Color.Silver;
            this.product_category.ItemHighLightForeColor = System.Drawing.Color.White;
            this.product_category.ItemTopMargin = 3;
            this.product_category.Location = new System.Drawing.Point(328, 268);
            this.product_category.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.product_category.Name = "product_category";
            this.product_category.Size = new System.Drawing.Size(357, 41);
            this.product_category.TabIndex = 60;
            this.product_category.Text = null;
            this.product_category.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.product_category.TextLeftMargin = 5;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.BackColor = System.Drawing.Color.Transparent;
            this.label1.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(107, 38);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(109, 28);
            this.label1.TabIndex = 55;
            this.label1.Text = "Product ID";
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.BackColor = System.Drawing.Color.Transparent;
            this.label5.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.Location = new System.Drawing.Point(107, 268);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(94, 28);
            this.label5.TabIndex = 59;
            this.label5.Text = "Category";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.BackColor = System.Drawing.Color.Transparent;
            this.label2.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.Location = new System.Drawing.Point(107, 95);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(143, 28);
            this.label2.TabIndex = 56;
            this.label2.Text = "Product Name";
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.BackColor = System.Drawing.Color.Transparent;
            this.label4.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.Location = new System.Drawing.Point(107, 210);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(56, 28);
            this.label4.TabIndex = 58;
            this.label4.Text = "Price";
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.BackColor = System.Drawing.Color.Transparent;
            this.label3.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.Location = new System.Drawing.Point(107, 153);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(90, 28);
            this.label3.TabIndex = 57;
            this.label3.Text = "Quantity";
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 20;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.productdeletebutton2);
            this.bunifuPanel1.Controls.Add(this.productupdatebutton3);
            this.bunifuPanel1.Controls.Add(this.productinsertbutton1);
            this.bunifuPanel1.Controls.Add(this.product_id);
            this.bunifuPanel1.Controls.Add(this.label3);
            this.bunifuPanel1.Controls.Add(this.product_name);
            this.bunifuPanel1.Controls.Add(this.label4);
            this.bunifuPanel1.Controls.Add(this.product_qty);
            this.bunifuPanel1.Controls.Add(this.label2);
            this.bunifuPanel1.Controls.Add(this.product_price);
            this.bunifuPanel1.Controls.Add(this.label5);
            this.bunifuPanel1.Controls.Add(this.label1);
            this.bunifuPanel1.Controls.Add(this.product_category);
            this.bunifuPanel1.Location = new System.Drawing.Point(44, 63);
            this.bunifuPanel1.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(1308, 341);
            this.bunifuPanel1.TabIndex = 68;
            // 
            // productdeletebutton2
            // 
            this.productdeletebutton2.AllowAnimations = true;
            this.productdeletebutton2.AllowMouseEffects = true;
            this.productdeletebutton2.AllowToggling = false;
            this.productdeletebutton2.AnimationSpeed = 200;
            this.productdeletebutton2.AutoGenerateColors = false;
            this.productdeletebutton2.AutoRoundBorders = false;
            this.productdeletebutton2.AutoSizeLeftIcon = true;
            this.productdeletebutton2.AutoSizeRightIcon = true;
            this.productdeletebutton2.BackColor = System.Drawing.Color.Transparent;
            this.productdeletebutton2.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.productdeletebutton2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("productdeletebutton2.BackgroundImage")));
            this.productdeletebutton2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.productdeletebutton2.ButtonText = "Delete";
            this.productdeletebutton2.ButtonTextMarginLeft = 0;
            this.productdeletebutton2.ColorContrastOnClick = 45;
            this.productdeletebutton2.ColorContrastOnHover = 45;
            this.productdeletebutton2.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.productdeletebutton2.CustomizableEdges = borderEdges1;
            this.productdeletebutton2.DialogResult = System.Windows.Forms.DialogResult.None;
            this.productdeletebutton2.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.productdeletebutton2.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.productdeletebutton2.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.productdeletebutton2.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.productdeletebutton2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.productdeletebutton2.ForeColor = System.Drawing.Color.Black;
            this.productdeletebutton2.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.productdeletebutton2.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.productdeletebutton2.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.productdeletebutton2.IconMarginLeft = 11;
            this.productdeletebutton2.IconPadding = 10;
            this.productdeletebutton2.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.productdeletebutton2.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.productdeletebutton2.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.productdeletebutton2.IconSize = 25;
            this.productdeletebutton2.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.productdeletebutton2.IdleBorderRadius = 30;
            this.productdeletebutton2.IdleBorderThickness = 1;
            this.productdeletebutton2.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.productdeletebutton2.IdleIconLeftImage = null;
            this.productdeletebutton2.IdleIconRightImage = null;
            this.productdeletebutton2.IndicateFocus = false;
            this.productdeletebutton2.Location = new System.Drawing.Point(903, 212);
            this.productdeletebutton2.Margin = new System.Windows.Forms.Padding(4);
            this.productdeletebutton2.Name = "productdeletebutton2";
            this.productdeletebutton2.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.productdeletebutton2.OnDisabledState.BorderRadius = 30;
            this.productdeletebutton2.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.productdeletebutton2.OnDisabledState.BorderThickness = 1;
            this.productdeletebutton2.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.productdeletebutton2.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.productdeletebutton2.OnDisabledState.IconLeftImage = null;
            this.productdeletebutton2.OnDisabledState.IconRightImage = null;
            this.productdeletebutton2.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(114)))), ((int)(((byte)(30)))));
            this.productdeletebutton2.onHoverState.BorderRadius = 30;
            this.productdeletebutton2.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.productdeletebutton2.onHoverState.BorderThickness = 1;
            this.productdeletebutton2.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(114)))), ((int)(((byte)(30)))));
            this.productdeletebutton2.onHoverState.ForeColor = System.Drawing.Color.White;
            this.productdeletebutton2.onHoverState.IconLeftImage = null;
            this.productdeletebutton2.onHoverState.IconRightImage = null;
            this.productdeletebutton2.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.productdeletebutton2.OnIdleState.BorderRadius = 30;
            this.productdeletebutton2.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.productdeletebutton2.OnIdleState.BorderThickness = 1;
            this.productdeletebutton2.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.productdeletebutton2.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.productdeletebutton2.OnIdleState.IconLeftImage = null;
            this.productdeletebutton2.OnIdleState.IconRightImage = null;
            this.productdeletebutton2.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(114)))), ((int)(((byte)(30)))));
            this.productdeletebutton2.OnPressedState.BorderRadius = 30;
            this.productdeletebutton2.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.productdeletebutton2.OnPressedState.BorderThickness = 1;
            this.productdeletebutton2.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(114)))), ((int)(((byte)(30)))));
            this.productdeletebutton2.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.productdeletebutton2.OnPressedState.IconLeftImage = null;
            this.productdeletebutton2.OnPressedState.IconRightImage = null;
            this.productdeletebutton2.Size = new System.Drawing.Size(271, 68);
            this.productdeletebutton2.TabIndex = 84;
            this.productdeletebutton2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.productdeletebutton2.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.productdeletebutton2.TextMarginLeft = 0;
            this.productdeletebutton2.TextPadding = new System.Windows.Forms.Padding(0);
            this.productdeletebutton2.UseDefaultRadiusAndThickness = true;
            this.productdeletebutton2.Click += new System.EventHandler(this.productdeletebutton2_Click);
            // 
            // productupdatebutton3
            // 
            this.productupdatebutton3.AllowAnimations = true;
            this.productupdatebutton3.AllowMouseEffects = true;
            this.productupdatebutton3.AllowToggling = false;
            this.productupdatebutton3.AnimationSpeed = 200;
            this.productupdatebutton3.AutoGenerateColors = false;
            this.productupdatebutton3.AutoRoundBorders = false;
            this.productupdatebutton3.AutoSizeLeftIcon = true;
            this.productupdatebutton3.AutoSizeRightIcon = true;
            this.productupdatebutton3.BackColor = System.Drawing.Color.Transparent;
            this.productupdatebutton3.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.productupdatebutton3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("productupdatebutton3.BackgroundImage")));
            this.productupdatebutton3.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.productupdatebutton3.ButtonText = "Update";
            this.productupdatebutton3.ButtonTextMarginLeft = 0;
            this.productupdatebutton3.ColorContrastOnClick = 45;
            this.productupdatebutton3.ColorContrastOnHover = 45;
            this.productupdatebutton3.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.productupdatebutton3.CustomizableEdges = borderEdges2;
            this.productupdatebutton3.DialogResult = System.Windows.Forms.DialogResult.None;
            this.productupdatebutton3.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.productupdatebutton3.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.productupdatebutton3.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.productupdatebutton3.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.productupdatebutton3.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.productupdatebutton3.ForeColor = System.Drawing.Color.Black;
            this.productupdatebutton3.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.productupdatebutton3.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.productupdatebutton3.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.productupdatebutton3.IconMarginLeft = 11;
            this.productupdatebutton3.IconPadding = 10;
            this.productupdatebutton3.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.productupdatebutton3.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.productupdatebutton3.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.productupdatebutton3.IconSize = 25;
            this.productupdatebutton3.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.productupdatebutton3.IdleBorderRadius = 30;
            this.productupdatebutton3.IdleBorderThickness = 1;
            this.productupdatebutton3.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.productupdatebutton3.IdleIconLeftImage = null;
            this.productupdatebutton3.IdleIconRightImage = null;
            this.productupdatebutton3.IndicateFocus = false;
            this.productupdatebutton3.Location = new System.Drawing.Point(903, 137);
            this.productupdatebutton3.Margin = new System.Windows.Forms.Padding(4);
            this.productupdatebutton3.Name = "productupdatebutton3";
            this.productupdatebutton3.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.productupdatebutton3.OnDisabledState.BorderRadius = 30;
            this.productupdatebutton3.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.productupdatebutton3.OnDisabledState.BorderThickness = 1;
            this.productupdatebutton3.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.productupdatebutton3.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.productupdatebutton3.OnDisabledState.IconLeftImage = null;
            this.productupdatebutton3.OnDisabledState.IconRightImage = null;
            this.productupdatebutton3.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(114)))), ((int)(((byte)(30)))));
            this.productupdatebutton3.onHoverState.BorderRadius = 30;
            this.productupdatebutton3.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.productupdatebutton3.onHoverState.BorderThickness = 1;
            this.productupdatebutton3.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(114)))), ((int)(((byte)(30)))));
            this.productupdatebutton3.onHoverState.ForeColor = System.Drawing.Color.White;
            this.productupdatebutton3.onHoverState.IconLeftImage = null;
            this.productupdatebutton3.onHoverState.IconRightImage = null;
            this.productupdatebutton3.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.productupdatebutton3.OnIdleState.BorderRadius = 30;
            this.productupdatebutton3.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.productupdatebutton3.OnIdleState.BorderThickness = 1;
            this.productupdatebutton3.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.productupdatebutton3.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.productupdatebutton3.OnIdleState.IconLeftImage = null;
            this.productupdatebutton3.OnIdleState.IconRightImage = null;
            this.productupdatebutton3.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(114)))), ((int)(((byte)(30)))));
            this.productupdatebutton3.OnPressedState.BorderRadius = 30;
            this.productupdatebutton3.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.productupdatebutton3.OnPressedState.BorderThickness = 1;
            this.productupdatebutton3.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(114)))), ((int)(((byte)(30)))));
            this.productupdatebutton3.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.productupdatebutton3.OnPressedState.IconLeftImage = null;
            this.productupdatebutton3.OnPressedState.IconRightImage = null;
            this.productupdatebutton3.Size = new System.Drawing.Size(271, 68);
            this.productupdatebutton3.TabIndex = 83;
            this.productupdatebutton3.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.productupdatebutton3.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.productupdatebutton3.TextMarginLeft = 0;
            this.productupdatebutton3.TextPadding = new System.Windows.Forms.Padding(0);
            this.productupdatebutton3.UseDefaultRadiusAndThickness = true;
            this.productupdatebutton3.Click += new System.EventHandler(this.productupdatebutton3_Click);
            // 
            // productinsertbutton1
            // 
            this.productinsertbutton1.AllowAnimations = true;
            this.productinsertbutton1.AllowMouseEffects = true;
            this.productinsertbutton1.AllowToggling = false;
            this.productinsertbutton1.AnimationSpeed = 200;
            this.productinsertbutton1.AutoGenerateColors = false;
            this.productinsertbutton1.AutoRoundBorders = false;
            this.productinsertbutton1.AutoSizeLeftIcon = true;
            this.productinsertbutton1.AutoSizeRightIcon = true;
            this.productinsertbutton1.BackColor = System.Drawing.Color.Transparent;
            this.productinsertbutton1.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.productinsertbutton1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("productinsertbutton1.BackgroundImage")));
            this.productinsertbutton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.productinsertbutton1.ButtonText = "Insert";
            this.productinsertbutton1.ButtonTextMarginLeft = 0;
            this.productinsertbutton1.ColorContrastOnClick = 45;
            this.productinsertbutton1.ColorContrastOnHover = 45;
            this.productinsertbutton1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.productinsertbutton1.CustomizableEdges = borderEdges3;
            this.productinsertbutton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.productinsertbutton1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.productinsertbutton1.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.productinsertbutton1.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.productinsertbutton1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.productinsertbutton1.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.productinsertbutton1.ForeColor = System.Drawing.Color.Black;
            this.productinsertbutton1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.productinsertbutton1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.productinsertbutton1.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.productinsertbutton1.IconMarginLeft = 11;
            this.productinsertbutton1.IconPadding = 10;
            this.productinsertbutton1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.productinsertbutton1.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.productinsertbutton1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.productinsertbutton1.IconSize = 25;
            this.productinsertbutton1.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.productinsertbutton1.IdleBorderRadius = 30;
            this.productinsertbutton1.IdleBorderThickness = 1;
            this.productinsertbutton1.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.productinsertbutton1.IdleIconLeftImage = null;
            this.productinsertbutton1.IdleIconRightImage = null;
            this.productinsertbutton1.IndicateFocus = false;
            this.productinsertbutton1.Location = new System.Drawing.Point(903, 62);
            this.productinsertbutton1.Margin = new System.Windows.Forms.Padding(4);
            this.productinsertbutton1.Name = "productinsertbutton1";
            this.productinsertbutton1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.productinsertbutton1.OnDisabledState.BorderRadius = 30;
            this.productinsertbutton1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.productinsertbutton1.OnDisabledState.BorderThickness = 1;
            this.productinsertbutton1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.productinsertbutton1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.productinsertbutton1.OnDisabledState.IconLeftImage = null;
            this.productinsertbutton1.OnDisabledState.IconRightImage = null;
            this.productinsertbutton1.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(114)))), ((int)(((byte)(30)))));
            this.productinsertbutton1.onHoverState.BorderRadius = 30;
            this.productinsertbutton1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.productinsertbutton1.onHoverState.BorderThickness = 1;
            this.productinsertbutton1.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(114)))), ((int)(((byte)(30)))));
            this.productinsertbutton1.onHoverState.ForeColor = System.Drawing.Color.White;
            this.productinsertbutton1.onHoverState.IconLeftImage = null;
            this.productinsertbutton1.onHoverState.IconRightImage = null;
            this.productinsertbutton1.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.productinsertbutton1.OnIdleState.BorderRadius = 30;
            this.productinsertbutton1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.productinsertbutton1.OnIdleState.BorderThickness = 1;
            this.productinsertbutton1.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.productinsertbutton1.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.productinsertbutton1.OnIdleState.IconLeftImage = null;
            this.productinsertbutton1.OnIdleState.IconRightImage = null;
            this.productinsertbutton1.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(114)))), ((int)(((byte)(30)))));
            this.productinsertbutton1.OnPressedState.BorderRadius = 30;
            this.productinsertbutton1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.productinsertbutton1.OnPressedState.BorderThickness = 1;
            this.productinsertbutton1.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(114)))), ((int)(((byte)(30)))));
            this.productinsertbutton1.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.productinsertbutton1.OnPressedState.IconLeftImage = null;
            this.productinsertbutton1.OnPressedState.IconRightImage = null;
            this.productinsertbutton1.Size = new System.Drawing.Size(271, 68);
            this.productinsertbutton1.TabIndex = 82;
            this.productinsertbutton1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.productinsertbutton1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.productinsertbutton1.TextMarginLeft = 0;
            this.productinsertbutton1.TextPadding = new System.Windows.Forms.Padding(0);
            this.productinsertbutton1.UseDefaultRadiusAndThickness = true;
            this.productinsertbutton1.Click += new System.EventHandler(this.productinsertbutton1_Click);
            // 
            // bunifuDataGridView1
            // 
            this.bunifuDataGridView1.AllowCustomTheming = true;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView1.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.bunifuDataGridView1.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.bunifuDataGridView1.BackgroundColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.bunifuDataGridView1.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.bunifuDataGridView1.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.bunifuDataGridView1.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.bunifuDataGridView1.ColumnHeadersHeight = 40;
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView1.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.CurrentTheme.GridColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.CurrentTheme.Name = null;
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.bunifuDataGridView1.DefaultCellStyle = dataGridViewCellStyle3;
            this.bunifuDataGridView1.EnableHeadersVisualStyles = false;
            this.bunifuDataGridView1.GridColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuDataGridView1.HeaderBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.bunifuDataGridView1.HeaderBgColor = System.Drawing.Color.Empty;
            this.bunifuDataGridView1.HeaderForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView1.Location = new System.Drawing.Point(7, 9);
            this.bunifuDataGridView1.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.bunifuDataGridView1.Name = "bunifuDataGridView1";
            this.bunifuDataGridView1.RowHeadersVisible = false;
            this.bunifuDataGridView1.RowHeadersWidth = 51;
            this.bunifuDataGridView1.RowTemplate.Height = 40;
            this.bunifuDataGridView1.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.bunifuDataGridView1.Size = new System.Drawing.Size(1295, 235);
            this.bunifuDataGridView1.TabIndex = 69;
            this.bunifuDataGridView1.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            this.bunifuDataGridView1.CellContentClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.bunifuDataGridView1_CellContentClick);
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label6.Location = new System.Drawing.Point(16, 431);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(317, 41);
            this.label6.TabIndex = 70;
            this.label6.Text = "MANAGE PRODUCTS";
            // 
            // categorydropdownsearchbar1
            // 
            this.categorydropdownsearchbar1.AllowDrop = true;
            this.categorydropdownsearchbar1.BackColor = System.Drawing.Color.Transparent;
            this.categorydropdownsearchbar1.BackgroundColor = System.Drawing.Color.White;
            this.categorydropdownsearchbar1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(218)))), ((int)(((byte)(223)))));
            this.categorydropdownsearchbar1.BorderRadius = 10;
            this.categorydropdownsearchbar1.Color = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(218)))), ((int)(((byte)(223)))));
            this.categorydropdownsearchbar1.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.categorydropdownsearchbar1.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.categorydropdownsearchbar1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.categorydropdownsearchbar1.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.categorydropdownsearchbar1.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.categorydropdownsearchbar1.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.categorydropdownsearchbar1.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.categorydropdownsearchbar1.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.categorydropdownsearchbar1.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.categorydropdownsearchbar1.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.categorydropdownsearchbar1.FillDropDown = true;
            this.categorydropdownsearchbar1.FillIndicator = false;
            this.categorydropdownsearchbar1.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.categorydropdownsearchbar1.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.categorydropdownsearchbar1.ForeColor = System.Drawing.Color.Black;
            this.categorydropdownsearchbar1.FormattingEnabled = true;
            this.categorydropdownsearchbar1.Icon = null;
            this.categorydropdownsearchbar1.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.categorydropdownsearchbar1.IndicatorColor = System.Drawing.Color.Gray;
            this.categorydropdownsearchbar1.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.categorydropdownsearchbar1.ItemBackColor = System.Drawing.Color.White;
            this.categorydropdownsearchbar1.ItemBorderColor = System.Drawing.Color.White;
            this.categorydropdownsearchbar1.ItemForeColor = System.Drawing.Color.Black;
            this.categorydropdownsearchbar1.ItemHeight = 35;
            this.categorydropdownsearchbar1.ItemHighLightColor = System.Drawing.Color.Silver;
            this.categorydropdownsearchbar1.ItemHighLightForeColor = System.Drawing.Color.White;
            this.categorydropdownsearchbar1.ItemTopMargin = 3;
            this.categorydropdownsearchbar1.Location = new System.Drawing.Point(671, 434);
            this.categorydropdownsearchbar1.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.categorydropdownsearchbar1.Name = "categorydropdownsearchbar1";
            this.categorydropdownsearchbar1.Size = new System.Drawing.Size(359, 41);
            this.categorydropdownsearchbar1.TabIndex = 68;
            this.categorydropdownsearchbar1.Text = null;
            this.categorydropdownsearchbar1.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.categorydropdownsearchbar1.TextLeftMargin = 5;
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.BackColor = System.Drawing.Color.Transparent;
            this.label7.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label7.Location = new System.Drawing.Point(16, 11);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(177, 41);
            this.label7.TabIndex = 71;
            this.label7.Text = "PRODUCTS";
            this.label7.Click += new System.EventHandler(this.label7_Click);
            // 
            // bunifuPanel2
            // 
            this.bunifuPanel2.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.bunifuPanel2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel2.BackgroundImage")));
            this.bunifuPanel2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel2.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel2.BorderRadius = 10;
            this.bunifuPanel2.BorderThickness = 1;
            this.bunifuPanel2.Controls.Add(this.bunifuDataGridView1);
            this.bunifuPanel2.Location = new System.Drawing.Point(44, 486);
            this.bunifuPanel2.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.bunifuPanel2.Name = "bunifuPanel2";
            this.bunifuPanel2.ShowBorders = true;
            this.bunifuPanel2.Size = new System.Drawing.Size(1308, 252);
            this.bunifuPanel2.TabIndex = 72;
            // 
            // productsearchbutton1
            // 
            this.productsearchbutton1.AllowAnimations = true;
            this.productsearchbutton1.AllowMouseEffects = true;
            this.productsearchbutton1.AllowToggling = false;
            this.productsearchbutton1.AnimationSpeed = 200;
            this.productsearchbutton1.AutoGenerateColors = false;
            this.productsearchbutton1.AutoRoundBorders = false;
            this.productsearchbutton1.AutoSizeLeftIcon = true;
            this.productsearchbutton1.AutoSizeRightIcon = true;
            this.productsearchbutton1.BackColor = System.Drawing.Color.Transparent;
            this.productsearchbutton1.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.productsearchbutton1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("productsearchbutton1.BackgroundImage")));
            this.productsearchbutton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.productsearchbutton1.ButtonText = "Search";
            this.productsearchbutton1.ButtonTextMarginLeft = 0;
            this.productsearchbutton1.ColorContrastOnClick = 45;
            this.productsearchbutton1.ColorContrastOnHover = 45;
            this.productsearchbutton1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.productsearchbutton1.CustomizableEdges = borderEdges4;
            this.productsearchbutton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.productsearchbutton1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.productsearchbutton1.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.productsearchbutton1.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.productsearchbutton1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.productsearchbutton1.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.productsearchbutton1.ForeColor = System.Drawing.Color.Black;
            this.productsearchbutton1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.productsearchbutton1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.productsearchbutton1.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.productsearchbutton1.IconMarginLeft = 11;
            this.productsearchbutton1.IconPadding = 10;
            this.productsearchbutton1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.productsearchbutton1.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.productsearchbutton1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.productsearchbutton1.IconSize = 25;
            this.productsearchbutton1.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.productsearchbutton1.IdleBorderRadius = 30;
            this.productsearchbutton1.IdleBorderThickness = 1;
            this.productsearchbutton1.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.productsearchbutton1.IdleIconLeftImage = null;
            this.productsearchbutton1.IdleIconRightImage = null;
            this.productsearchbutton1.IndicateFocus = false;
            this.productsearchbutton1.Location = new System.Drawing.Point(1048, 434);
            this.productsearchbutton1.Margin = new System.Windows.Forms.Padding(4);
            this.productsearchbutton1.Name = "productsearchbutton1";
            this.productsearchbutton1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.productsearchbutton1.OnDisabledState.BorderRadius = 30;
            this.productsearchbutton1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.productsearchbutton1.OnDisabledState.BorderThickness = 1;
            this.productsearchbutton1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.productsearchbutton1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.productsearchbutton1.OnDisabledState.IconLeftImage = null;
            this.productsearchbutton1.OnDisabledState.IconRightImage = null;
            this.productsearchbutton1.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(114)))), ((int)(((byte)(30)))));
            this.productsearchbutton1.onHoverState.BorderRadius = 30;
            this.productsearchbutton1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.productsearchbutton1.onHoverState.BorderThickness = 1;
            this.productsearchbutton1.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(114)))), ((int)(((byte)(30)))));
            this.productsearchbutton1.onHoverState.ForeColor = System.Drawing.Color.White;
            this.productsearchbutton1.onHoverState.IconLeftImage = null;
            this.productsearchbutton1.onHoverState.IconRightImage = null;
            this.productsearchbutton1.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.productsearchbutton1.OnIdleState.BorderRadius = 30;
            this.productsearchbutton1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.productsearchbutton1.OnIdleState.BorderThickness = 1;
            this.productsearchbutton1.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.productsearchbutton1.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.productsearchbutton1.OnIdleState.IconLeftImage = null;
            this.productsearchbutton1.OnIdleState.IconRightImage = null;
            this.productsearchbutton1.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(114)))), ((int)(((byte)(30)))));
            this.productsearchbutton1.OnPressedState.BorderRadius = 30;
            this.productsearchbutton1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.productsearchbutton1.OnPressedState.BorderThickness = 1;
            this.productsearchbutton1.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(114)))), ((int)(((byte)(30)))));
            this.productsearchbutton1.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.productsearchbutton1.OnPressedState.IconLeftImage = null;
            this.productsearchbutton1.OnPressedState.IconRightImage = null;
            this.productsearchbutton1.Size = new System.Drawing.Size(146, 38);
            this.productsearchbutton1.TabIndex = 85;
            this.productsearchbutton1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.productsearchbutton1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.productsearchbutton1.TextMarginLeft = 0;
            this.productsearchbutton1.TextPadding = new System.Windows.Forms.Padding(0);
            this.productsearchbutton1.UseDefaultRadiusAndThickness = true;
            this.productsearchbutton1.Click += new System.EventHandler(this.productsearchbutton1_Click);
            // 
            // refreshbutton1
            // 
            this.refreshbutton1.AllowAnimations = true;
            this.refreshbutton1.AllowMouseEffects = true;
            this.refreshbutton1.AllowToggling = false;
            this.refreshbutton1.AnimationSpeed = 200;
            this.refreshbutton1.AutoGenerateColors = false;
            this.refreshbutton1.AutoRoundBorders = false;
            this.refreshbutton1.AutoSizeLeftIcon = true;
            this.refreshbutton1.AutoSizeRightIcon = true;
            this.refreshbutton1.BackColor = System.Drawing.Color.Transparent;
            this.refreshbutton1.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.refreshbutton1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("refreshbutton1.BackgroundImage")));
            this.refreshbutton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.refreshbutton1.ButtonText = "Refresh";
            this.refreshbutton1.ButtonTextMarginLeft = 0;
            this.refreshbutton1.ColorContrastOnClick = 45;
            this.refreshbutton1.ColorContrastOnHover = 45;
            this.refreshbutton1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.refreshbutton1.CustomizableEdges = borderEdges5;
            this.refreshbutton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.refreshbutton1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.refreshbutton1.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.refreshbutton1.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.refreshbutton1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.refreshbutton1.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.refreshbutton1.ForeColor = System.Drawing.Color.Black;
            this.refreshbutton1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.refreshbutton1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.refreshbutton1.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.refreshbutton1.IconMarginLeft = 11;
            this.refreshbutton1.IconPadding = 10;
            this.refreshbutton1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.refreshbutton1.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.refreshbutton1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.refreshbutton1.IconSize = 25;
            this.refreshbutton1.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.refreshbutton1.IdleBorderRadius = 30;
            this.refreshbutton1.IdleBorderThickness = 1;
            this.refreshbutton1.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.refreshbutton1.IdleIconLeftImage = null;
            this.refreshbutton1.IdleIconRightImage = null;
            this.refreshbutton1.IndicateFocus = false;
            this.refreshbutton1.Location = new System.Drawing.Point(1200, 434);
            this.refreshbutton1.Margin = new System.Windows.Forms.Padding(4);
            this.refreshbutton1.Name = "refreshbutton1";
            this.refreshbutton1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.refreshbutton1.OnDisabledState.BorderRadius = 30;
            this.refreshbutton1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.refreshbutton1.OnDisabledState.BorderThickness = 1;
            this.refreshbutton1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.refreshbutton1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.refreshbutton1.OnDisabledState.IconLeftImage = null;
            this.refreshbutton1.OnDisabledState.IconRightImage = null;
            this.refreshbutton1.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(114)))), ((int)(((byte)(30)))));
            this.refreshbutton1.onHoverState.BorderRadius = 30;
            this.refreshbutton1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.refreshbutton1.onHoverState.BorderThickness = 1;
            this.refreshbutton1.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(114)))), ((int)(((byte)(30)))));
            this.refreshbutton1.onHoverState.ForeColor = System.Drawing.Color.White;
            this.refreshbutton1.onHoverState.IconLeftImage = null;
            this.refreshbutton1.onHoverState.IconRightImage = null;
            this.refreshbutton1.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.refreshbutton1.OnIdleState.BorderRadius = 30;
            this.refreshbutton1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.refreshbutton1.OnIdleState.BorderThickness = 1;
            this.refreshbutton1.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(191)))), ((int)(((byte)(18)))));
            this.refreshbutton1.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.refreshbutton1.OnIdleState.IconLeftImage = null;
            this.refreshbutton1.OnIdleState.IconRightImage = null;
            this.refreshbutton1.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(114)))), ((int)(((byte)(30)))));
            this.refreshbutton1.OnPressedState.BorderRadius = 30;
            this.refreshbutton1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.refreshbutton1.OnPressedState.BorderThickness = 1;
            this.refreshbutton1.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(114)))), ((int)(((byte)(30)))));
            this.refreshbutton1.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.refreshbutton1.OnPressedState.IconLeftImage = null;
            this.refreshbutton1.OnPressedState.IconRightImage = null;
            this.refreshbutton1.Size = new System.Drawing.Size(146, 38);
            this.refreshbutton1.TabIndex = 86;
            this.refreshbutton1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.refreshbutton1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.refreshbutton1.TextMarginLeft = 0;
            this.refreshbutton1.TextPadding = new System.Windows.Forms.Padding(0);
            this.refreshbutton1.UseDefaultRadiusAndThickness = true;
            this.refreshbutton1.Click += new System.EventHandler(this.refreshbutton1_Click);
            // 
            // sub_products
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(252)))), ((int)(((byte)(252)))));
            this.ClientSize = new System.Drawing.Size(1397, 752);
            this.Controls.Add(this.refreshbutton1);
            this.Controls.Add(this.productsearchbutton1);
            this.Controls.Add(this.bunifuPanel2);
            this.Controls.Add(this.label7);
            this.Controls.Add(this.categorydropdownsearchbar1);
            this.Controls.Add(this.label6);
            this.Controls.Add(this.bunifuPanel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Margin = new System.Windows.Forms.Padding(4);
            this.Name = "sub_products";
            this.Palette = this.kryptonPalette1;
            this.PaletteMode = ComponentFactory.Krypton.Toolkit.PaletteMode.Custom;
            this.Text = "sub_products";
            this.Load += new System.EventHandler(this.sub_products_Load);
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuDataGridView1)).EndInit();
            this.bunifuPanel2.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private ComponentFactory.Krypton.Toolkit.KryptonPalette kryptonPalette1;
        private Bunifu.UI.WinForms.BunifuTextBox product_id;
        private Bunifu.UI.WinForms.BunifuTextBox product_name;
        private Bunifu.UI.WinForms.BunifuTextBox product_qty;
        private Bunifu.UI.WinForms.BunifuTextBox product_price;
        private Bunifu.UI.WinForms.BunifuDropdown product_category;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label3;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuDataGridView bunifuDataGridView1;
        private System.Windows.Forms.Label label6;
        private Bunifu.UI.WinForms.BunifuDropdown categorydropdownsearchbar1;
        private System.Windows.Forms.Label label7;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton productdeletebutton2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton productupdatebutton3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton productinsertbutton1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton productsearchbutton1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton refreshbutton1;
    }
}